import { createInitialProjectGraph } from '../core/projectEngine';
import { applyConsistencyEvaluation, evaluateProjectConsistency, getOpenConsistencyIssues, resolveConsistencyIssue } from '../engines/projectConsistencyEngine';
import { applyConfirmationCorrection, getConfirmedKnowledge, getPendingConfirmations, interpretProjectMessage, mergeProjectKnowledge, resolveConfirmation } from '../engines/projectKnowledgeEngine';
import type { ProjectGraph } from '../types/project';
import type { ProjectKnowledgeEntity, ProjectKnowledgeValue } from '../types/projectKnowledge';

function assert(condition:unknown,message:string):asserts condition{if(!condition)throw new Error(message);}
let sequence=0;
function knowledge(key:string,type:ProjectKnowledgeEntity['type'],value:ProjectKnowledgeValue,status:ProjectKnowledgeEntity['status']='confirmed'):ProjectKnowledgeEntity{const id=`entity-${++sequence}`,timestamp='2026-01-01T00:00:00.000Z';return{id,type,key,label:key,value,normalizedValue:JSON.stringify(value),status,confidence:.99,provenance:{source:'manual',extractionMethod:'manual'},evidence:[{id:`evidence-${sequence}`,source:'manual',quote:key,createdAt:timestamp}],relatedModules:[],relatedEntities:[],createdAt:timestamp,updatedAt:timestamp,confirmedAt:status==='confirmed'?timestamp:undefined};}
function withKnowledge(...entities:ProjectKnowledgeEntity[]):ProjectGraph{const graph=createInitialProjectGraph();graph.knowledge!.entities=entities;return graph;}

let kicks=createInitialProjectGraph();const message='Hacer cada par cuesta COP 80.000 y quiero venderlo a COP 220.000.';kicks=mergeProjectKnowledge(kicks,interpretProjectMessage({message,graph:kicks}));
const costRequest=getPendingConfirmations(kicks).find(item=>item.intent==='clarify_cost_scope');assert(costRequest,'Kicks debe solicitar confirmación de alcance.');
const confirmed=resolveConfirmation(kicks,costRequest.id,'accepted');assert(getConfirmedKnowledge(confirmed).some(item=>item.key==='production_cost_unit'&&item.confirmedAt),'Confirmar debe actualizar entidad y confirmedAt.');assert(getPendingConfirmations(confirmed).every(item=>item.id!==costRequest.id),'La solicitud confirmada debe cerrarse.');

const corrected=applyConfirmationCorrection(kicks,costRequest.id,'Los 80.000 son solo materiales.');const costHistory=corrected.knowledge!.entities.filter(item=>item.key==='production_cost_unit');assert(costHistory.length===2&&costHistory.some(item=>item.status==='superseded'),'Corregir debe conservar y superseder historial.');assert(costHistory.some(item=>item.status!=='superseded'&&typeof item.value==='object'&&(item.value as {scope?:string}).scope==='materials'),'La corrección debe aplicar scope materials.');assert(corrected.knowledge!.entities.some(item=>item.key==='intended_sale_price'&&item.status!=='superseded'),'Debe conservar precio.');assert(corrected.knowledge!.entities.some(item=>item.key==='preliminary_unit_spread'),'Debe conservar spread preliminar.');
const rejected=resolveConfirmation(kicks,costRequest.id,'rejected');assert(rejected.knowledge!.entities.some(item=>item.key==='production_cost_unit'&&item.status==='contradicted'),'Rechazar debe conservar entidad contradicha.');

let team=withKnowledge(knowledge('team_size','fact',5),knowledge('employee_compensation','financial_fact',{amount:2500000,period:'month',currency:'COP'}));team.tools.budgetLines=[{id:'personal',category:'Personal',concept:'Nómina mensual',quantity:1,unit:'mes',unitValue:7000000,vatRate:0,withholdingRate:0,otherTaxes:0,status:'proposed',responsible:'',provider:'',estimatedDate:'',actualDate:'',source:'manual'}];const teamResult=evaluateProjectConsistency({graph:team});const teamIssue=teamResult.issues.find(item=>item.type==='team_budget_mismatch');assert(teamIssue?.expected===12500000&&teamIssue.actual===7000000&&teamIssue.difference===5500000,'Debe detectar diferencia equipo-presupuesto.');

const capacity=evaluateProjectConsistency({graph:withKnowledge(knowledge('expected_attendance','fact',500),knowledge('venue_capacity','fact',300))}).issues.find(item=>item.type==='capacity_mismatch');assert(capacity?.severity==='critical','Aforo 500 contra capacidad 300 debe ser critical.');

const activity=evaluateProjectConsistency({graph:withKnowledge(knowledge('sound_rental_activity','activity',{activity:'Alquilar sistema de sonido',costConcept:'alquiler de sistema de sonido',important:true}))}).issues;assert(activity.some(item=>item.type==='possible_unbudgeted_activity'&&item.severity==='warning'),'Debe advertir actividad sin costo asociado.');assert(activity.every(item=>item.expected===undefined||item.type!=='possible_unbudgeted_activity'),'No debe inventar monto faltante.');

team=applyConsistencyEvaluation(team,teamResult);const openTeam=getOpenConsistencyIssues(team).find(item=>item.type==='team_budget_mismatch');assert(openTeam,'El issue debe persistir abierto.');team.knowledge!.entities.push(knowledge('personnel_budget_scope','fact',{period:'first_month',coveredEmployeeCount:2,partial:true}));team=applyConsistencyEvaluation(team,evaluateProjectConsistency({graph:team}));assert(!getOpenConsistencyIssues(team).some(item=>item.type==='team_budget_mismatch'),'Una explicación de cobertura parcial debe cerrar el issue, no volverlo contradicción.');

let temporal=withKnowledge(knowledge('launch_date','timeline_fact',{kind:'timeline',value:'2026-11-20',temporalType:'date',precision:'day',tentative:false}));temporal.tools.scheduleItems=[{id:'production',name:'Producción',description:'Producción necesaria',startsAt:'2026-11-01',endsAt:'2026-11-30',responsible:'Pedro',status:'planned',budgetLineId:null,documentIds:[],tasks:[],milestone:true,activityId:null}];const temporalIssue=evaluateProjectConsistency({graph:temporal}).issues.find(item=>item.type==='temporal_mismatch');assert(temporalIssue?.severity==='critical','Producción posterior al lanzamiento debe ser critical.');

let dates=createInitialProjectGraph();dates=mergeProjectKnowledge(dates,interpretProjectMessage({message:'El evento será el 18 de octubre.',graph:dates}));dates=mergeProjectKnowledge(dates,interpretProjectMessage({message:'En realidad el evento será el 25 de octubre.',graph:dates}));const dateHistory=dates.knowledge!.entities.filter(item=>item.key==='project_date');assert(dateHistory.length===2&&dateHistory.filter(item=>item.status!=='superseded').length===1,'La fecha corregida debe superseder la anterior.');assert(!evaluateProjectConsistency({graph:dates}).issues.some(item=>item.type==='knowledge_contradiction'),'Una versión superseded no debe generar contradicción.');

const conflictingDates=withKnowledge(knowledge('event_date','timeline_fact',{kind:'timeline',value:'2026-10-18',temporalType:'date',precision:'day',tentative:false}),knowledge('event_date','timeline_fact',{kind:'timeline',value:'2026-10-25',temporalType:'date',precision:'day',tentative:false}));assert(evaluateProjectConsistency({graph:conflictingDates}).issues.some(item=>item.type==='knowledge_contradiction'&&item.severity==='critical'),'Dos fechas activas confirmadas deben generar contradicción.');

const duplicateFirst=applyConsistencyEvaluation(temporal,evaluateProjectConsistency({graph:temporal}));const duplicateSecond=applyConsistencyEvaluation(duplicateFirst,evaluateProjectConsistency({graph:duplicateFirst}));assert(duplicateSecond.consistency!.issues.filter(item=>item.type==='temporal_mismatch').length===1,'Los issues deben deduplicarse.');const issueId=duplicateSecond.consistency!.issues.find(item=>item.type==='temporal_mismatch')!.id;const resolvedIssue=resolveConsistencyIssue(duplicateSecond,issueId,'resolved','Fecha ajustada por producción.');assert(resolvedIssue.consistency!.issues.find(item=>item.id===issueId)?.status==='resolved','Un issue debe poder resolverse conservando historial.');

const serialized=JSON.parse(JSON.stringify(resolvedIssue)) as ProjectGraph;assert(serialized.knowledge?.confirmations&&serialized.consistency?.issues,'Confirmaciones e issues deben ser serializables con el grafo.');
console.log('Executive Engine V2.3: OK');
