import { createId, now } from '../core/projectEngine';
import { totalDeLinea } from '../core/budgetMath';
import type { ProjectBudgetLine } from '../types/project';
import type { FinancialKnowledgeValue, ProjectKnowledgeEntity, ProjectKnowledgeState } from '../types/projectKnowledge';
import type { CanonicalFinancialItem, FinancialAuthorityState, FinancialChangeSummary, FinancialConflict, FinancialDivergenceReport, FinancialDomainEvent, FinancialItemStatus, FinancialProposal, Money } from '../types/financialAuthority';

const normalize=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const money=(amount:number,currency='COP'):Money=>({amount,currency});
const graphTotal=(l:ProjectBudgetLine)=>totalDeLinea(l);
export const financialProposalKey=(projectId:string,ids:string[])=>`financial-proposal:${projectId}:${ids.slice().sort().join(',')}`;
export const financialCommandKey=(projectId:string,proposalId:string,command='accept')=>`financial-command:${projectId}:${proposalId}:${command}`;

export function materializeFinancialKnowledge(input:{projectId:string;knowledgeEntity:ProjectKnowledgeEntity;quantityEntity?:ProjectKnowledgeEntity;allowProposed?:boolean}):FinancialProposal|null{
  const {knowledgeEntity}=input;const allowed=input.allowProposed?['proposed','confirmed','validated']:['confirmed','validated'];if(knowledgeEntity.type!=='financial_fact'||!allowed.includes(knowledgeEntity.status)||typeof knowledgeEntity.value!=='object'||Array.isArray(knowledgeEntity.value))return null;
  const value=knowledgeEntity.value as FinancialKnowledgeValue; if(value.kind!=='financial'||!Number.isFinite(value.amount))return null;
  const qValue=input.quantityEntity?.value;const structuredQuantity=typeof qValue==='object'&&!Array.isArray(qValue)&&qValue!==null&&typeof (qValue as Record<string,unknown>).quantity==='number'?(qValue as Record<string,number>).quantity:undefined;const quantity=typeof qValue==='number'?qValue:structuredQuantity??value.quantity??1;const ids=[knowledgeEntity.id,...(input.quantityEntity?[input.quantityEntity.id]:[])];const timestamp=now();const concept=knowledgeEntity.label||value.concept;
  const reason=knowledgeEntity.key==='artist_performance_fee'?'Referencia preliminar; las tarifas pueden variar según trayectoria y requieren desglose y aprobación antes de incorporarse al presupuesto.':'Conocimiento financiero confirmado; requiere aprobación separada para incorporarlo al presupuesto.';
  return{id:createId(),projectId:input.projectId,sourceKnowledgeIds:ids,direction:value.scope==='sale_price'?'income':'expense',concept,quantity,unit:value.unit??'unidad',unitPrice:money(value.amount,value.currency),calculatedTotal:money(quantity*value.amount,value.currency),proposedStatus:'estimated',confidence:knowledgeEntity.confidence,reason,status:'pending',idempotencyKey:financialProposalKey(input.projectId,ids),createdAt:timestamp,updatedAt:timestamp};
}

export function createProposal(state:FinancialAuthorityState,proposal:FinancialProposal){const existing=state.proposals.find(p=>p.idempotencyKey===proposal.idempotencyKey);if(existing)return{state,proposal:existing,created:false};const event:eventShape={type:'financial_proposal_created',entityId:proposal.id,idempotencyKey:`event:${proposal.idempotencyKey}`};return{state:{...state,proposals:[...state.proposals,proposal],events:[...state.events,toEvent(proposal.projectId,event)]},proposal,created:true};}
type eventShape=Pick<FinancialDomainEvent,'type'|'entityId'|'idempotencyKey'> & Partial<FinancialDomainEvent>;
function toEvent(projectId:string,event:eventShape):FinancialDomainEvent{return{id:event.id??createId(),projectId,entityId:event.entityId,type:event.type,actorId:event.actorId,timestamp:event.timestamp??now(),before:event.before,after:event.after,reason:event.reason,idempotencyKey:event.idempotencyKey};}

export function acceptFinancialProposal(state:FinancialAuthorityState,proposalId:string,actorId?:string){const proposal=state.proposals.find(p=>p.id===proposalId);if(!proposal)throw new Error('Financial proposal not found.');const key=financialCommandKey(proposal.projectId,proposal.id);const duplicate=state.items.find(i=>i.idempotencyKey===key);if(duplicate)return{state,item:duplicate,created:false};if(!['pending','edited'].includes(proposal.status))throw new Error(`Financial proposal cannot be accepted from ${proposal.status}.`);const timestamp=now();const zero=money(0,proposal.unitPrice.currency);const item:CanonicalFinancialItem={id:createId(),projectId:proposal.projectId,direction:proposal.direction,category:'Por clasificar',concept:proposal.concept,description:proposal.reason,quantity:proposal.quantity,unit:proposal.unit,unitPrice:proposal.unitPrice,discount:zero,vat:zero,withholding:zero,otherTaxes:zero,total:proposal.calculatedTotal,status:proposal.proposedStatus,notes:'',evidence:[],source:'conversation',sourceKnowledgeIds:proposal.sourceKnowledgeIds,proposalId:proposal.id,idempotencyKey:key,version:1,createdAt:timestamp,updatedAt:timestamp};const accepted={...proposal,status:'accepted' as const,updatedAt:timestamp};const events=[toEvent(proposal.projectId,{type:'financial_proposal_accepted',entityId:proposal.id,actorId,idempotencyKey:`event:${key}:proposal`}),toEvent(proposal.projectId,{type:'financial_item_created',entityId:item.id,actorId,after:item as unknown as Record<string,unknown>,idempotencyKey:`event:${key}:item`}),toEvent(proposal.projectId,{type:'financial_item_linked_to_knowledge',entityId:item.id,actorId,reason:proposal.sourceKnowledgeIds.join(','),idempotencyKey:`event:${key}:link`})];return{state:{items:[...state.items,item],proposals:state.proposals.map(p=>p.id===proposal.id?accepted:p),events:[...state.events,...events]},item,created:true};}

export function updateFinancialItem(state:FinancialAuthorityState,input:{itemId:string;expectedVersion:number;unitPrice?:Money;quantity?:number;status?:FinancialItemStatus;actorId?:string;reason?:string}){
  const old=state.items.find(i=>i.id===input.itemId);if(!old)throw new Error('Financial item not found.');if(old.version!==input.expectedVersion){const conflict:FinancialConflict={kind:'version_conflict',itemId:old.id,expectedVersion:input.expectedVersion,actualVersion:old.version,message:'El presupuesto cambió desde que lo abriste.'};return{state,conflict};}
  const quantity=input.quantity??old.quantity,unitPrice=input.unitPrice??old.unitPrice;const subtotal=quantity*unitPrice.amount;const total=money(Math.max(0,subtotal-old.discount.amount+old.vat.amount-old.withholding.amount+old.otherTaxes.amount),unitPrice.currency);const timestamp=now();const next={...old,quantity,unitPrice,total,status:input.status??old.status,version:old.version+1,updatedAt:timestamp};const type=next.status!==old.status?'financial_item_status_changed' as const:'financial_item_updated' as const;const event=toEvent(old.projectId,{type,entityId:old.id,actorId:input.actorId,before:old as unknown as Record<string,unknown>,after:next as unknown as Record<string,unknown>,reason:input.reason,idempotencyKey:`financial-update:${old.id}:${next.version}`});return{state:{...state,items:state.items.map(i=>i.id===old.id?next:i),events:[...state.events,event]},item:next,change:summarizeFinancialChange(old,next)};
}

export function syncFinancialItemToKnowledge(state:ProjectKnowledgeState,item:CanonicalFinancialItem):ProjectKnowledgeState{const timestamp=now();const active=state.entities.filter(e=>e.type==='financial_fact'&&e.operationalRef?.entityId===item.id&&e.status!=='superseded');const nextId=createId();const superseded=state.entities.map(e=>active.some(a=>a.id===e.id)?{...e,status:'superseded' as const,supersededBy:nextId,updatedAt:timestamp}:e);const previous=active[0];const entity:ProjectKnowledgeEntity={id:nextId,type:'financial_fact',key:previous?.key??`financial_item_${item.id}`,label:item.concept,value:{kind:'financial',concept:item.concept,amount:item.unitPrice.amount,currency:item.unitPrice.currency,quantity:item.quantity,unit:item.unit,scope:item.direction==='income'?'forecast_income':'cost',taxIncluded:'unknown'},status:'confirmed',confidence:1,provenance:{source:'manual',actorId:undefined,extractionMethod:'manual'},evidence:[],relatedModules:['budget'],relatedEntities:[],operationalRef:{domain:'financial',entityId:item.id},createdAt:timestamp,updatedAt:timestamp,confirmedAt:timestamp};return{...state,entities:[...superseded,entity],updatedAt:timestamp};}

export function summarizeFinancialChange(old:CanonicalFinancialItem,current:CanonicalFinancialItem):FinancialChangeSummary{const difference=current.total.amount-old.total.amount;return{itemId:current.id,projectId:current.projectId,concept:current.concept,previousUnitPrice:old.unitPrice,currentUnitPrice:current.unitPrice,previousTotal:old.total,currentTotal:current.total,difference:money(difference,current.total.currency),summary:[`Cambió el costo unitario de ${current.concept} de ${format(old.unitPrice)} a ${format(current.unitPrice)}.`,`Con ${current.quantity} ${current.unit}, el total pasa de ${format(old.total)} a ${format(current.total)}.`,`Cambio total: ${format(money(difference,current.total.currency))}.`]};}
const format=(m:Money)=>`${m.currency} ${m.amount.toLocaleString('es-CO')}`;

export function detectFinancialDivergence(projectId:string,graphLines:ProjectBudgetLine[],items:CanonicalFinancialItem[]):FinancialDivergenceReport{const divergences:FinancialDivergenceReport['divergences']=[];const used=new Set<string>();for(const line of graphLines){const match=items.find(i=>!used.has(i.id)&&(i.id===line.id||normalize(i.concept)===normalize(line.concept)));if(!match){divergences.push({kind:'graph_only',graphLineId:line.id,concept:line.concept,detail:'La línea existe solo en ProjectGraph.'});continue;}used.add(match.id);if(Math.abs(line.unitValue-match.unitPrice.amount)>=.01)divergences.push({kind:'value_mismatch',graphLineId:line.id,canonicalItemId:match.id,concept:line.concept,detail:`Valor graph ${line.unitValue}; canonical ${match.unitPrice.amount}.`});const status=mapLegacyStatus(line.status);if(status!==match.status)divergences.push({kind:'status_mismatch',graphLineId:line.id,canonicalItemId:match.id,concept:line.concept,detail:`Estado graph ${line.status}; canonical ${match.status}.`});const subtotal=line.quantity*line.unitValue,graphVat=subtotal*line.vatRate/100,graphWithholding=subtotal*line.withholdingRate/100;if(Math.abs(graphVat-match.vat.amount)>=.01||Math.abs(graphWithholding-match.withholding.amount)>=.01||Math.abs(line.otherTaxes-match.otherTaxes.amount)>=.01)divergences.push({kind:'tax_mismatch',graphLineId:line.id,canonicalItemId:match.id,concept:line.concept,detail:`Impuestos graph IVA ${graphVat}, retención ${graphWithholding}, otros ${line.otherTaxes}; canonical IVA ${match.vat.amount}, retención ${match.withholding.amount}, otros ${match.otherTaxes.amount}.`});if(Math.abs(graphTotal(line)-match.total.amount)>=.01)divergences.push({kind:'total_mismatch',graphLineId:line.id,canonicalItemId:match.id,concept:line.concept,detail:`Total graph ${graphTotal(line)}; canonical ${match.total.amount}.`});if(line.responsible&&line.responsible!==match.responsibleId)divergences.push({kind:'responsible_mismatch',graphLineId:line.id,canonicalItemId:match.id,concept:line.concept,detail:'Los responsables no coinciden.'});}for(const item of items)if(!used.has(item.id))divergences.push({kind:'table_only',canonicalItemId:item.id,concept:item.concept,detail:'La línea existe solo en la autoridad canónica.'});return{projectId,comparedAt:now(),divergences,hasConflicts:divergences.length>0,autoMerged:false};}
export function mapLegacyStatus(status:ProjectBudgetLine['status']):FinancialItemStatus{return status==='proposed'?'proposed':status==='approved'?'approved':status==='committed'?'committed':'paid';}
export function calculateFundingGap(items:CanonicalFinancialItem[]):Money{const currency=items[0]?.total.currency??'COP';const costs=items.filter(i=>i.direction==='expense'&&!['cancelled'].includes(i.status)).reduce((n,i)=>n+i.total.amount,0);const funding=items.filter(i=>i.direction==='income'&&['approved','committed','invoiced','executed','paid'].includes(i.status)).reduce((n,i)=>n+i.total.amount,0);return money(Math.max(0,costs-funding),currency);}
export const initialFinancialAuthorityState=():FinancialAuthorityState=>({items:[],proposals:[],events:[]});
