import { createId, createInitialProjectConsistencyState, now } from '../core/projectEngine';
import type { ProjectBudgetLine, ProjectGraph, ProjectModuleId } from '../types/project';
import type { ConsistencyIssue, ConsistencyIssueStatus, ConsistencyIssueType, ConsistencyResult } from '../types/projectConsistency';
import type { ProjectKnowledgeEntity, TimelineKnowledgeValue } from '../types/projectKnowledge';
import { getActiveKnowledge, getConfirmedKnowledge } from './projectKnowledgeEngine';

const norm=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const record=(entity:ProjectKnowledgeEntity)=>typeof entity.value==='object'&&!Array.isArray(entity.value)?entity.value as Record<string,unknown>:{};
const numeric=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)?value:null;
const total=(line:ProjectBudgetLine)=>{const subtotal=line.quantity*line.unitValue;return subtotal+subtotal*line.vatRate/100-subtotal*line.withholdingRate/100+line.otherTaxes;};
const comparablePeriod=(left:unknown,right:string)=>{if(typeof left!=='string'||!left.trim()||!right.trim())return false;const a=norm(left),b=norm(right);return a===b||(a.startsWith('month')&&/mes|month/.test(b))||(a.startsWith('mes')&&/mes|month/.test(b));};
const fingerprint=(type:ConsistencyIssueType,ids:string[],expected?:string|number,actual?:string|number)=>[type,...ids.slice().sort(),expected??'',actual??''].join('|');

function issue(type:ConsistencyIssueType,severity:ConsistencyIssue['severity'],title:string,explanation:string,entityIds:string[],relatedModules:ProjectModuleId[],confidence:number,suggestedAction:string,values:Pick<ConsistencyIssue,'expected'|'actual'|'difference'>={}):ConsistencyIssue{const timestamp=now();return{id:createId(),fingerprint:fingerprint(type,entityIds,values.expected,values.actual),type,severity,title,explanation,entityIds,relatedModules,...values,status:'open',confidence,suggestedAction,createdAt:timestamp,updatedAt:timestamp};}

function teamBudgetIssues(graph:ProjectGraph,confirmed:ProjectKnowledgeEntity[]){const scope=confirmed.find(item=>item.key==='personnel_budget_scope');if(scope&&record(scope).partial===true)return[];const count=confirmed.find(item=>['team_size','employee_count'].includes(item.key??''));const compensation=confirmed.find(item=>['employee_compensation','compensation_per_person'].includes(item.key??''));if(!count||!compensation)return[];const quantity=numeric(typeof count.value==='number'?count.value:record(count).quantity),unitCost=numeric(record(compensation).amount),period=record(compensation).period;if(quantity===null||unitCost===null)return[];const lines=graph.tools.budgetLines.filter(line=>/personal|nomina|equipo|talento humano/.test(norm(`${line.category} ${line.concept}`))&&comparablePeriod(period,line.unit));if(!lines.length)return[];const expected=quantity*unitCost,actual=lines.reduce((sum,line)=>sum+total(line),0);if(Math.abs(expected-actual)<1)return[];return[issue('team_budget_mismatch','warning','Equipo y presupuesto podrían usar cifras diferentes',`Tienes ${quantity} integrantes con un valor declarado de COP ${unitCost.toLocaleString('es-CO')} cada uno para el periodo ${String(period)}. Eso daría COP ${expected.toLocaleString('es-CO')}, mientras las líneas comparables de personal suman COP ${actual.toLocaleString('es-CO')}. Puede tratarse de periodos, coberturas o costos parciales diferentes.`,[count.id,compensation.id],['team','budget'],.96,'Revisar el periodo y la cobertura del presupuesto de personal.',{expected,actual,difference:expected-actual})];}

function financialTotalIssues(confirmed:ProjectKnowledgeEntity[]){const issues:ConsistencyIssue[]=[];for(const item of confirmed.filter(entity=>entity.type==='financial_fact')){const value=record(item),quantity=numeric(value.quantity),unitCost=numeric(value.unitCost),declared=numeric(value.total);if(quantity===null||unitCost===null||declared===null)continue;const expected=quantity*unitCost;if(Math.abs(expected-declared)<1)continue;issues.push(issue('financial_total_mismatch','warning','Cantidad, costo unitario y total requieren revisión',`La cantidad ${quantity} por el costo unitario COP ${unitCost.toLocaleString('es-CO')} da COP ${expected.toLocaleString('es-CO')}, pero el total declarado es COP ${declared.toLocaleString('es-CO')}. Alguna cifra puede tener un alcance distinto.`,[item.id],['budget'],.98,'Confirmar cantidad, costo unitario y alcance del total.',{expected,actual:declared,difference:expected-declared}));}return issues;}

function capacityIssues(confirmed:ProjectKnowledgeEntity[]){const attendance=confirmed.find(item=>item.key==='expected_attendance'),capacity=confirmed.find(item=>item.key==='venue_capacity');const expected=numeric(attendance?.value),actual=numeric(capacity?.value);if(!attendance||!capacity||expected===null||actual===null||expected<=actual)return[];return[issue('capacity_mismatch','critical','El aforo esperado supera la capacidad registrada',`Esperas ${expected} asistentes y el espacio tiene capacidad registrada para ${actual}. Conviene revisar aforo, sede o formato antes de comprometer la operación.`,[attendance.id,capacity.id],['community','timeline','risks'],.99,'Revisar la sede o ajustar el aforo previsto.',{expected,actual,difference:expected-actual})];}

function activityIssues(graph:ProjectGraph,confirmed:ProjectKnowledgeEntity[]){const issues:ConsistencyIssue[]=[];for(const activity of confirmed.filter(item=>item.type==='activity'&&item.confidence>=.8)){const value=record(activity);const important=value.important!==false;const name=String(value.activity??activity.label);const costConcept=typeof value.costConcept==='string'?value.costConcept:typeof value.budgetConcept==='string'?value.budgetConcept:structuredCostConcept(activity.key??'',name);if(important&&costConcept){const matched=graph.tools.budgetLines.some(line=>semanticMatch(costConcept,`${line.category} ${line.concept}`));if(!matched)issues.push(issue('possible_unbudgeted_activity','warning','Actividad sin costo o aporte asociado',`La actividad “${name}” parece requerir ${costConcept}, pero no encuentro una línea presupuestal relacionada. Podría cubrirse con recursos propios, aporte en especie, intercambio o patrocinio.`,[activity.id],['activities','budget'],.86,'Confirmar cómo se cubrirá esta actividad.'));}const responsible=value.responsible??activity.relatedEntities.find(relation=>relation.type==='responsible_for');if(important&&!responsible)issues.push(issue('activity_without_responsible','warning','Actividad importante sin responsable',`La actividad “${name}” está suficientemente definida, pero todavía no tiene una responsabilidad asociada.`,[activity.id],['activities','team'],.84,'Asignar o confirmar quién coordina esta actividad.'));}return issues;}
function structuredCostConcept(key:string,name:string){const text=norm(`${key} ${name}`);if(/alquil.*sonido|sound rental/.test(text))return'alquiler de sistema de sonido';if(/transport/.test(text))return'transporte';if(/impres/.test(text))return'impresión';if(/contrat/.test(text))return'contratación';if(/compra/.test(text))return'compra';if(/produccion/.test(text))return'producción';return'';}
function semanticMatch(expected:string,actual:string){const left=new Set(norm(expected).split(' ').filter(word=>word.length>3)),right=norm(actual);return[...left].some(word=>right.includes(word));}

function temporalIssues(graph:ProjectGraph,confirmed:ProjectKnowledgeEntity[]){const launch=confirmed.find(item=>['launch_date','launch_period','project_date'].includes(item.key??'')&&record(item).kind==='timeline');if(!launch)return[];const value=launch.value as TimelineKnowledgeValue;const launchDate=parseDate(value.value);if(!launchDate)return[];const late=graph.tools.scheduleItems.filter(item=>/produccion|production/.test(norm(`${item.name} ${item.description}`))&&parseDate(item.endsAt)&&parseDate(item.endsAt)!>launchDate);if(!late.length)return[];const latest=late.sort((a,b)=>String(b.endsAt).localeCompare(String(a.endsAt)))[0];return[issue('temporal_mismatch','critical','Una actividad necesaria termina después de la fecha prevista',`La fecha registrada para el lanzamiento es ${value.value}, pero “${latest.name}” termina el ${latest.endsAt}. Si corresponden a la misma edición, conviene revisar el cronograma o la fecha.`,[launch.id],['timeline','activities','risks'],.97,'Revisar la fecha de lanzamiento o el fin de producción.',{expected:value.value,actual:latest.endsAt})];}
function parseDate(value:string){const parsed=new Date(value);return Number.isNaN(parsed.getTime())?null:parsed;}

function contradictionIssues(confirmed:ProjectKnowledgeEntity[]){const issues:ConsistencyIssue[]=[];const keys=[...new Set(confirmed.map(item=>item.key).filter((key):key is string=>Boolean(key)))];for(const key of keys){const versions=confirmed.filter(item=>item.key===key);const values=[...new Set(versions.map(item=>item.normalizedValue??JSON.stringify(item.value)))];if(versions.length<2||values.length<2)continue;issues.push(issue('knowledge_contradiction','critical','Dos afirmaciones confirmadas no coinciden',`Encontré más de un valor confirmado para “${versions[0].label}”. Puede tratarse de ediciones o contextos diferentes; conviene aclararlo antes de usar este dato.`,versions.map(item=>item.id),versions.flatMap(item=>item.relatedModules),.99,'Confirmar cuál valor corresponde al contexto actual.'));}return issues;}

export function evaluateProjectConsistency({graph}:{graph:ProjectGraph}):ConsistencyResult{const confirmed=getConfirmedKnowledge(graph),detected=[...financialTotalIssues(confirmed),...teamBudgetIssues(graph,confirmed),...capacityIssues(confirmed),...activityIssues(graph,confirmed),...temporalIssues(graph,confirmed),...contradictionIssues(confirmed)];const previous=graph.consistency?.issues??[];const merged=detected.map(candidate=>{const old=previous.find(item=>item.fingerprint===candidate.fingerprint);return old?{...candidate,id:old.id,status:old.status,createdAt:old.createdAt,resolvedAt:old.resolvedAt,resolutionNote:old.resolutionNote}:candidate;});for(const old of previous)if(!merged.some(item=>item.fingerprint===old.fingerprint))merged.push(old.status==='open'||old.status==='acknowledged'?{...old,status:'resolved',resolvedAt:now(),updatedAt:now(),resolutionNote:old.resolutionNote??'La condición dejó de estar presente en la evaluación.'}:old);const result={issues:merged,evaluatedAt:now()};traceConsistency(result);return result;}
export function applyConsistencyEvaluation(graph:ProjectGraph,result:ConsistencyResult):ProjectGraph{return{...graph,consistency:{version:1,issues:result.issues,evaluatedAt:result.evaluatedAt},updatedAt:now()};}
export function resolveConsistencyIssue(graph:ProjectGraph,issueId:string,status:Extract<ConsistencyIssueStatus,'acknowledged'|'resolved'|'dismissed'>,note?:string):ProjectGraph{const base=graph.consistency??createInitialProjectConsistencyState(),timestamp=now();return{...graph,consistency:{...base,issues:base.issues.map(item=>item.id===issueId?{...item,status,updatedAt:timestamp,resolvedAt:status==='resolved'||status==='dismissed'?timestamp:item.resolvedAt,resolutionNote:note??item.resolutionNote}:item)},updatedAt:timestamp};}
export function getOpenConsistencyIssues(graph:ProjectGraph){return(graph.consistency?.issues??[]).filter(item=>item.status==='open').sort((a,b)=>severity(b.severity)-severity(a.severity)||b.confidence-a.confidence);}
export function getTopConsistencyIssue(graph:ProjectGraph){return getOpenConsistencyIssues(graph).find(item=>item.confidence>=.8)??null;}
function severity(value:ConsistencyIssue['severity']){return value==='critical'?3:value==='warning'?2:1;}
function traceConsistency(result:ConsistencyResult){if(process.env.NODE_ENV==='development')console.debug('[ExecutiveEngineV2 consistency]',{issues:result.issues.map(({id,type,severity,status,confidence})=>({id,type,severity,status,confidence}))});}
