import { createId, createInitialProjectKnowledgeState, now } from '../core/projectEngine';
import type { EvidenceSource, ProjectGraph, ProjectModuleId, ProjectPatch } from '../types/project';
import type { ConfirmationRequest, FinancialKnowledgeValue, InterpretProjectMessageInput, ProjectDriver, ProjectInterpretationResult, ProjectKnowledgeEntity, ProjectKnowledgeState, ProjectKnowledgeValue, ProjectType, TimelineKnowledgeValue } from '../types/projectKnowledge';
import { detectFinancialSignals } from './budgetSignalProcessor';

const normalize=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
const money=(value:string)=>Number(value.replace(/[^0-9]/g,''));
const normalizedValue=(value:ProjectKnowledgeValue)=>typeof value==='object'?JSON.stringify(value,Object.keys(value).sort()):normalize(String(value));

interface Draft { type:ProjectKnowledgeEntity['type']; key?:string; label:string; value:ProjectKnowledgeValue; status:ProjectKnowledgeEntity['status']; confidence:number; modules:ProjectModuleId[]; method?:ProjectKnowledgeEntity['provenance']['extractionMethod']; quote?:string; relations?:ProjectKnowledgeEntity['relatedEntities']; }

function entity(draft:Draft,source:EvidenceSource,sourceReferenceId:string|undefined,message:string):ProjectKnowledgeEntity{
  const timestamp=now(); const evidenceId=createId();
  return {id:createId(),type:draft.type,key:draft.key,label:draft.label,value:draft.value,normalizedValue:normalizedValue(draft.value),status:draft.status,confidence:draft.confidence,provenance:{source,messageId:source==='conversation'?sourceReferenceId:undefined,documentId:source==='document'?sourceReferenceId:undefined,extractionMethod:draft.method??'explicit'},evidence:[{id:evidenceId,source,quote:draft.quote??message,createdAt:timestamp}],relatedModules:draft.modules,relatedEntities:draft.relations??[],createdAt:timestamp,updatedAt:timestamp};
}

function confirmation(entityIds:string[],intent:string,question:string,reason:string,impact:ConfirmationRequest['impact'],type:ConfirmationRequest['type']='require_confirmation'):ConfirmationRequest{return{id:createId(),entityIds,type,intent,question,reason,impact,status:'pending',createdAt:now()};}

function financialDrafts(message:string,graph:ProjectGraph):Draft[]{
  const text=normalize(message); const signals=detectFinancialSignals(message); const drafts:Draft[]=[];
  let cost=signals.find(signal=>signal.kind==='cost'&&signal.amount!==null); let price=signals.find(signal=>signal.kind==='price'&&signal.amount!==null);
  const artistFee=/(?:(?:cada\s+)?artistas?\s+(?:cobraria|cobrarian|cobra|cobran|costaria|costarian)|cada\s+uno\s+(?:cuesta|costaria|cobraria))\s+(?:unos?|aproximadamente|alrededor de)?\s*(?:cop\s*|\$\s*)?([0-9][0-9.,]*)\s*(millones?|mil)?/.exec(text);
  if(artistFee){let amount=money(artistFee[1]);if(artistFee[2]?.startsWith('millon'))amount*=1_000_000;else if(artistFee[2]==='mil')amount*=1_000;const known=(graph.knowledge?.entities??[]).find(item=>item.key==='artist_requirement'&&item.status!=='superseded');const quantity=typeof known?.value==='object'&&!Array.isArray(known.value)&&known.value!==null&&typeof (known.value as {quantity?:unknown}).quantity==='number'?(known.value as {quantity:number}).quantity:1;cost={id:'artist-fee',kind:'cost',concept:'Honorarios de artistas',amount,currency:'COP',quantity,unit:'artista',status:'requires_breakdown',source:'conversation',requiresConfirmation:true};}
  const ticket=/(?:cobrar|precio(?: previsto)?)(?:\s+un)?\s+ticket\s+(?:de|a)?\s*(?:cop\s*|\$\s*)?([0-9][0-9.,]*)/.exec(text);
  if(ticket)price={id:'ticket-price',kind:'price',concept:'Precio previsto del ticket',amount:money(ticket[1]),currency:'COP',quantity:1,unit:'ticket',status:'declared',source:'conversation',requiresConfirmation:true};
  if(!cost){const match=/(?:el )?costo(?: es|:| de)?\s*(?:cop\s*|\$\s*)?([0-9][0-9.,]*)/.exec(text)??/([0-9][0-9.,]*)\s+(?:son|corresponden a)\s+(?:solo|solamente)\s+(?:los )?materiales/.exec(text);if(match)cost={id:'derived',kind:'cost',concept:'Costo declarado',amount:money(match[1]),currency:'COP',quantity:1,unit:'unit',status:'requires_breakdown',source:'conversation',requiresConfirmation:true};}
  const unit=cost?.unit??'unit';
  if(cost?.amount!==null&&cost?.amount!==undefined){const materialsOnly=/solo (?:son )?(?:materiales|materia prima)|solamente (?:son )?materiales/.test(text),artistCost=cost.unit==='artista';const value:FinancialKnowledgeValue={kind:'financial',concept:artistCost?'artist_performance_fee':materialsOnly?'materials_cost':'production_cost',amount:cost.amount,currency:'COP',quantity:cost.quantity??1,unit,scope:artistCost?'cost':materialsOnly?'materials':'unknown',taxIncluded:'unknown'};drafts.push({type:'financial_fact',key:artistCost?'artist_performance_fee':'production_cost_unit',label:artistCost?'Honorarios de artistas':materialsOnly?'Costo de materiales declarado':'Costo de producción declarado',value,status:'proposed',confidence:artistCost?.88:.96,modules:['budget'],quote:message});}
  if(price?.amount!==null&&price?.amount!==undefined){const ticketPrice=price.unit==='ticket';const value:FinancialKnowledgeValue={kind:'financial',concept:ticketPrice?'intended_ticket_price':'intended_sale_price',amount:price.amount,currency:'COP',quantity:1,unit:price.unit??unit,scope:'sale_price',taxIncluded:'unknown'};drafts.push({type:'financial_fact',key:ticketPrice?'intended_ticket_price':'intended_sale_price',label:ticketPrice?'Precio previsto del ticket':'Precio de venta previsto',value,status:'proposed',confidence:.96,modules:['budget','sustainability']});}
  if(cost?.amount&&price?.amount){const value:FinancialKnowledgeValue={kind:'financial',concept:'preliminary_unit_spread',amount:price.amount-cost.amount,currency:'COP',quantity:1,unit,scope:'before_unallocated_costs',taxIncluded:'unknown'};drafts.push({type:'inference',key:'preliminary_unit_spread',label:'Diferencia unitaria preliminar',value,status:'proposed',confidence:.9,modules:['budget','sustainability'],method:'calculation'});}
  const funding=/(?:necesit(?:o|amos)|nos falta|conseguir)\s+(?:cop\s*|\$\s*)?([0-9][0-9.,]*)\s*(millones?|mil)?/.exec(text);if(funding){let amount=money(funding[1]);if(funding[2]?.startsWith('millon'))amount*=1_000_000;else if(funding[2]==='mil')amount*=1_000;drafts.push({type:'need',key:'funding_need',label:'Necesidad de financiación',value:{amount,currency:'COP',kind:'funding'},status:'proposed',confidence:.94,modules:['budget','opportunities']});}
  return drafts;
}

function temporalDrafts(message:string):Draft[]{const text=normalize(message);const month='enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre';const match=new RegExp(`\\b(?:el\\s+)?(\\d{1,2})?(?:\\s+de)?\\s*(${month})\\b`).exec(text);if(!match)return[];const tentative=/mas o menos|aproximadamente|tentativ|queremos|esperamos/.test(text);const value:TimelineKnowledgeValue={kind:'timeline',value:[match[1],match[2]].filter(Boolean).join(' '),temporalType:/antes de|deadline|fecha limite/.test(text)?'deadline':'date',precision:match[1]?'day':'month',tentative};return[{type:'timeline_fact',key:/lanz/.test(text)?'launch_period':'project_date',label:tentative?'Fecha o periodo previsto':'Fecha declarada',value,status:'proposed',confidence:match[1]?.length?.95:.85,modules:['timeline']}];}

function actorDrafts(message:string):Draft[]{const drafts:Draft[]=[];const regex=/\b([A-ZÁÉÍÓÚÑ][a-záéíóúñ]+)\s+(?:se encargara|se encargará|maneja|estara a cargo|estará a cargo)\s+de\s+([^,.]+?)(?=\s+y\s+[A-ZÁÉÍÓÚÑ]|[,.]|$)|\b([A-ZÁÉÍÓÚÑ][a-záéíóúñ]+)\s+de\s+(comunicaciones|produccion|producción)(?=[,.]|$)/g;let match:RegExpExecArray|null;while((match=regex.exec(message))){const name=match[1]??match[3],area=(match[2]??match[4]).trim();const actorKey=`actor:${normalize(name)}`;drafts.push({type:'actor',key:actorKey,label:`Actor: ${name}`,value:{name,actorType:'person'},status:'confirmed',confidence:.98,modules:['team']});drafts.push({type:'responsibility',key:`responsibility:${normalize(name)}:${normalize(area)}`,label:`${name}: ${area}`,value:{actor:name,responsibility:area},status:'proposed',confidence:.96,modules:['team','activities']});}return drafts;}

function generalDrafts(message:string):Draft[]{const text=normalize(message),drafts:Draft[]=[];
  const attendance=/(?:para|tuvo|esperamos?)\s+(?:unas?\s+)?([0-9][0-9.,]*)\s+(?:personas|asistentes)/.exec(text);if(attendance)drafts.push({type:'fact',key:/tuvo/.test(attendance[0])?'previous_attendance':'expected_attendance',label:/tuvo/.test(attendance[0])?'Asistencia histórica':'Asistencia esperada',value:money(attendance[1]),status:'confirmed',confidence:.97,modules:['community','timeline']});
  const artists=/(?:quiero|queremos|necesito|necesitamos|requiere|para|total de|seran)\s+(?:un\s+total\s+de\s+)?([0-9]+)\s+artistas/.exec(text);if(artists)drafts.push({type:'need',key:'artist_requirement',label:'Artistas requeridos',value:{resourceType:'artist',quantity:Number(artists[1])},status:'proposed',confidence:.95,modules:['team','activities']});
  if(/concierto|festival/.test(text))drafts.push({type:'activity',key:'main_activity',label:'Actividad principal: concierto/festival',value:{activity:'concierto',format:/festival/.test(text)?'festival':'concierto'},status:'proposed',confidence:.94,modules:['activities']});
  if(/artistas.*(?:diferentes|distintas) regiones.*colombia/.test(text))drafts.push({type:'fact',key:'artist_regional_context',label:'Artistas de distintas regiones de Colombia',value:{country:'Colombia',regionalDiversity:true},status:'proposed',confidence:.93,modules:['context','team']});
  if(/(?:trayectoria|experiencia).*(?:cobran|honorarios|pago)|(?:cobran|honorarios|pago).*trayectoria/.test(text))drafts.push({type:'constraint',key:'artist_fee_variability',label:'Honorarios variables según trayectoria',value:{variableBy:'trajectory',distributionDefined:false},status:'confirmed',confidence:.96,modules:['budget','team','risks']});
  if(/(?:pagar|remunerar).*(?:artistas)|(?:artistas).*(?:pagar|remunerar)/.test(text))drafts.push({type:'need',key:'artist_fee_need',label:'Remuneracion de artistas requerida',value:{costDomain:'artist_performance_fees'},status:'confirmed',confidence:.95,modules:['budget','team']});
  if(/(?:aun|todavia|no)\s+(?:no\s+)?se.*(?:dividir|distribuir).*(?:pago|honorario)|(?:pago|honorario).*(?:pendiente|sin definir)/.test(text))drafts.push({type:'constraint',key:'artist_fee_distribution_uncertainty',label:'Distribucion de honorarios pendiente',value:{distributionDefined:false},status:'confirmed',confidence:.95,modules:['budget','risks']});
  if(/(?:todavia|aun|no)\s+(?:no\s+)?(?:tenemos|tengo).*\b(?:espacio|venue|sede)\b|no tenemos espacio/.test(text))drafts.push({type:'need',key:'venue_need',label:'Espacio requerido',value:{resourceType:'venue',status:'missing'},status:'confirmed',confidence:.98,modules:['allies','opportunities','risks']});
  if(/no (?:tengo|tenemos).*(?:diseno|identidad).*(?:marca)|(?:diseno|identidad) de marca.*(?:pendiente|falta)/.test(text))drafts.push({type:'need',key:'brand_design_need',label:'Diseño de marca pendiente',value:{resourceType:'brand_design'},status:'confirmed',confidence:.98,modules:['identity','team','budget']});
  const need=/(?:necesit(?:o|amos)|nos falta)\s+(?:un|una|el|la)?\s*([^,.]+)/.exec(text);if(need&&!/\d/.test(need[1]))drafts.push({type:'need',key:`need:${normalize(need[1])}`,label:`Necesidad: ${need[1].trim()}`,value:need[1].trim(),status:'confirmed',confidence:.88,modules:['opportunities']});
  const resource=/(?:tenemos|contamos con)\s+(?:un|una|el|la)?\s*([^,.]+)/.exec(text);if(resource&&!/no tenemos/.test(text))drafts.push({type:'resource',key:`resource:${normalize(resource[1])}`,label:`Recurso disponible: ${resource[1].trim()}`,value:resource[1].trim(),status:'confirmed',confidence:.88,modules:['team','allies']});
  const years=/(?:llevamos|desde hace)\s+([a-z]+|\d+)\s+anos/.exec(text);if(years)drafts.push({type:'fact',key:'operational_history',label:'Trayectoria operativa',value:years[1],status:'confirmed',confidence:.96,modules:['evidence','impact']});
  const team=/(?:equipo de|somos)\s+([0-9]+)\s+personas/.exec(text);if(team)drafts.push({type:'fact',key:'historical_team_size',label:'Tamaño del equipo',value:Number(team[1]),status:'confirmed',confidence:.96,modules:['team']});
  const historicalBudget=/presupuesto de\s+(?:cop\s*|\$\s*)?([0-9][0-9.,]*)\s*(millones?|mil)?/.exec(text);if(historicalBudget){let amount=money(historicalBudget[1]);if(historicalBudget[2]?.startsWith('millon'))amount*=1_000_000;else if(historicalBudget[2]==='mil')amount*=1_000;drafts.push({type:'financial_fact',key:'historical_budget',label:'Presupuesto histórico',value:{kind:'financial',concept:'historical_budget',amount,currency:'COP',scope:'historical',taxIncluded:'unknown'},status:'confirmed',confidence:.96,modules:['budget','evidence']});}
  const production=/(?:tenemos que|debemos)\s+(producir\s+([0-9]+)\s+unidades[^,.]*)/.exec(text);if(production)drafts.push({type:'activity',key:'production_activity',label:'Actividad de producción',value:{activity:production[1],quantity:Number(production[2])},status:'proposed',confidence:.95,modules:['activities','timeline']});
  return drafts;}

function typeAndDrivers(message:string){const text=normalize(message),types:ProjectType[]=[],drivers:ProjectDriver[]=[];const financialSignals=detectFinancialSignals(message);const hasUnitEconomics=financialSignals.some(s=>s.kind==='cost')&&financialSignals.some(s=>s.kind==='price');if(/producto|unidades/.test(text)||hasUnitEconomics)types.push('product');if(/marca|empresa|negocio|vend/.test(text))types.push('business');if(/festival|evento/.test(text))types.push('event');if(/taller/.test(text))types.push('workshop');if(/experiencia/.test(text))types.push('experience');if(/performance|performan|obra artistica|proyecto artistico/.test(text))types.push('artistic_project');if(/investig/.test(text))types.push('research');if(/campana/.test(text))types.push('campaign');if(/comunidad|comunitari/.test(text))types.push('community_initiative');if(/problema|resolver/.test(text))drivers.push('problem');if(/necesit|nos falta/.test(text))drivers.push('need');if(/oportunidad/.test(text))drivers.push('opportunity');if(/quiero|deseo/.test(text))drivers.push('desire');if(/explor|todavia no se|todavía no sé/.test(text))drivers.push('exploration');if(/investig/.test(text))drivers.push('research');if(/convocatoria/.test(text))drivers.push('grant_or_call');return{types:[...new Set(types)],drivers:[...new Set(drivers)]};}

export function interpretProjectMessage(input:InterpretProjectMessageInput,patches:ProjectPatch[]=[]):ProjectInterpretationResult{
  const source=input.source??'conversation',signals=typeAndDrivers(input.message);const drafts=[...financialDrafts(input.message,input.graph),...temporalDrafts(input.message),...actorDrafts(input.message),...generalDrafts(input.message)];
  const entities=drafts.map(draft=>entity(draft,source,input.sourceReferenceId,input.message));const confirmations:ConfirmationRequest[]=[];const cost=entities.find(item=>item.key==='production_cost_unit');if(cost){confirmations.push(confirmation([cost.id],'clarify_cost_scope','¿Ese costo corresponde solo a materiales y fabricación o incluye también mano de obra, administración, impuestos, empaque, transporte y marketing?','El alcance del costo debe confirmarse antes de estimar margen o rentabilidad.','high'));}const artistFee=entities.find(item=>item.key==='artist_performance_fee');if(artistFee){confirmations.push(confirmation([artistFee.id],'clarify_artist_fee_model','¿Ese valor por artista es un promedio provisional o una tarifa base que después dividirás por categorías de trayectoria?','La variabilidad declarada hace necesario confirmar el modelo de honorarios.','high'));}
  for(const responsibility of entities.filter(item=>item.type==='responsibility'))confirmations.push(confirmation([responsibility.id],'clarify_responsibility',`¿Confirmas que ${responsibility.label}?`,'Una responsabilidad afecta la ejecución del proyecto.','high'));
  for(const date of entities.filter(item=>item.type==='timeline_fact'))confirmations.push(confirmation([date.id],'clarify_date_precision',`¿La fecha “${(date.value as TimelineKnowledgeValue).value}” es tentativa o ya está confirmada?`,'Las fechas que afectan la ejecución requieren confirmación explícita.','high'));
  const consolidated=/\b(?:llevamos|desde hace)\b/.test(normalize(input.message))&&['idea','exploration'].includes(input.graph.stage);const warnings:string[]=[];if(consolidated)warnings.push('possible_stage_mismatch');
  const parts=entities.filter(item=>item.type!=='inference').slice(0,4).map(item=>item.label);const inference=entities.find(item=>item.key==='preliminary_unit_spread');let summary=parts.length?`Entendí ${parts.join(', ')}.`:'Registré nueva información del proyecto.';if(inference)summary+=` La diferencia unitaria preliminar es COP ${(inference.value as FinancialKnowledgeValue).amount.toLocaleString('es-CO')}, pero no representa utilidad ni rentabilidad.`;if(cost)summary+=' Todavía debemos confirmar qué incluye exactamente ese costo.';
  const fee=entities.find(item=>item.key==='artist_performance_fee');const knownQuantity=(input.graph.knowledge?.entities??[]).find(item=>item.key==='artist_requirement'&&item.status!=='superseded');const rawQuantity=knownQuantity?.value;const quantity=typeof rawQuantity==='object'&&rawQuantity!==null&&!Array.isArray(rawQuantity)&&typeof (rawQuantity as {quantity?:unknown}).quantity==='number'?(rawQuantity as {quantity:number}).quantity:undefined;const organizedItems=entities.filter(item=>item.type!=='inference').map(item=>item.label).slice(0,8);if(fee&&typeof fee.value==='object'&&!Array.isArray(fee.value)){const value=fee.value as FinancialKnowledgeValue;const count=quantity??value.quantity??1;summary+=` Referencia preliminar: ${count} artistas por COP ${value.amount.toLocaleString('es-CO')} = COP ${(count*value.amount).toLocaleString('es-CO')}. Los honorarios varÃ­an segÃºn trayectoria y requieren desglose y aprobaciÃ³n.`;organizedItems.unshift(`Honorarios preliminares: ${count} artistas x COP ${value.amount.toLocaleString('es-CO')} = COP ${(count*value.amount).toLocaleString('es-CO')}`);}
  return{knowledgeEntities:entities,modulePatches:patches,confirmationRequests:confirmations,warnings,interpretationSummary:summary,organizedItems:organizedItems.slice(0,8),clarificationIntent:confirmations[0]?.intent,suggestedQuestion:confirmations[0]?.question,knowledgeLookupSuggested:/legal|derecho|impuesto|mercado|impacto/.test(normalize(input.message)),projectTypeSignals:signals.types,driverSignals:signals.drivers};
}

function sameSemanticValue(a:ProjectKnowledgeEntity,b:ProjectKnowledgeEntity){return a.type===b.type&&a.key===b.key&&a.normalizedValue===b.normalizedValue;}
export function mergeProjectKnowledge(graph:ProjectGraph,result:ProjectInterpretationResult):ProjectGraph{
  const base:ProjectKnowledgeState=graph.knowledge??createInitialProjectKnowledgeState();const existing=base.entities.map(item=>({...item}));const accepted:ProjectKnowledgeEntity[]=[];
  for(const candidate of result.knowledgeEntities){const duplicate=existing.find(item=>!item.supersededBy&&item.status!=='superseded'&&sameSemanticValue(item,candidate));if(duplicate)continue;const previous=candidate.key?existing.find(item=>item.key===candidate.key&&item.status!=='superseded'&&!item.supersededBy):undefined;const quote=normalize(candidate.evidence.map(item=>item.quote).join(' '));const explicitCorrection=/\b(?:en realidad|correccion|corrijo|no[, ]|solamente|solo son|son solo|son solamente|quise decir)\b/.test(quote)||candidate.relatedEntities.some(item=>item.type==='corrects');if(previous&&explicitCorrection){previous.status='superseded';previous.supersededBy=candidate.id;previous.updatedAt=now();candidate.relatedEntities=[...candidate.relatedEntities,{entityId:previous.id,type:'corrects'}];}existing.push(candidate);accepted.push(candidate);}
  const acceptedIds=new Set(accepted.map(item=>item.id));const confirmations=result.confirmationRequests.filter(request=>request.entityIds.some(id=>acceptedIds.has(id))&&!base.confirmations.some(old=>old.status==='pending'&&old.intent===request.intent&&old.entityIds.some(id=>request.entityIds.includes(id))));const types=[...new Set(result.projectTypeSignals)];const primary=base.projectType.primaryType??types[0];const secondary=[...new Set([...base.projectType.secondaryTypes,...types.filter(type=>type!==primary)])];const timestamp=now();return{...graph,knowledge:{version:1,entities:existing,confirmations:[...base.confirmations,...confirmations],projectType:{primaryType:primary,secondaryTypes:secondary,drivers:[...new Set([...base.projectType.drivers,...result.driverSignals])],confidence:types.length?Math.max(base.projectType.confidence,.85):base.projectType.confidence,updatedAt:timestamp},updatedAt:timestamp},updatedAt:timestamp};
}

export function resolveConfirmation(graph:ProjectGraph,confirmationId:string,status:'accepted'|'rejected'|'edited'|'dismissed'):ProjectGraph{
  const base=graph.knowledge??createInitialProjectKnowledgeState();const timestamp=now();const target=base.confirmations.find(item=>item.id===confirmationId);if(!target||target.status!=='pending')return graph;const targetEntities=base.entities.filter(item=>target.entityIds.includes(item.id));const targetKeys=new Set(targetEntities.map(item=>item.key).filter((key):key is string=>Boolean(key)));const entities=base.entities.map(item=>{if(target.entityIds.includes(item.id))return{...item,status:status==='accepted'?'confirmed' as const:status==='rejected'?'contradicted' as const:item.status,confirmedAt:status==='accepted'?timestamp:item.confirmedAt,updatedAt:timestamp};if(status==='accepted'&&item.key&&targetKeys.has(item.key)&&(item.status==='proposed'||item.status==='detected'||item.status==='unknown')){const replacement=targetEntities.find(entity=>entity.key===item.key);return{...item,status:'superseded' as const,supersededBy:replacement?.id,updatedAt:timestamp};}return item;});const next={...graph,knowledge:{...base,entities,confirmations:base.confirmations.map(item=>item.id===confirmationId?{...item,status,resolvedAt:timestamp}:item),updatedAt:timestamp},updatedAt:timestamp};traceConfirmationResolution(confirmationId,status);return next;
}

export function applyConfirmationCorrection(graph:ProjectGraph,confirmationId:string,correction:string):ProjectGraph{
  const base=graph.knowledge??createInitialProjectKnowledgeState();const request=base.confirmations.find(item=>item.id===confirmationId&&item.status==='pending');if(!request||!correction.trim())return graph;const target=base.entities.find(item=>request.entityIds.includes(item.id)&&item.status!=='superseded');if(!target)return resolveConfirmation(graph,confirmationId,'edited');let result=interpretProjectMessage({message:correction,graph,source:'conversation'});
  if(request.intent==='clarify_cost_scope'&&target.key==='production_cost_unit'&&!result.knowledgeEntities.some(item=>item.key==='production_cost_unit')){const scope=/material/.test(normalize(correction))?'materials':/total|todos los costos|incluye todo/.test(normalize(correction))?'total':normalize(correction);const value={...(target.value as FinancialKnowledgeValue),concept:scope==='materials'?'materials_cost':'production_cost',scope};const corrected:ProjectKnowledgeEntity={...target,id:createId(),label:scope==='materials'?'Costo de materiales declarado':'Costo de producción corregido',value,normalizedValue:normalizedValue(value),status:'proposed',confidence:.98,provenance:{source:'conversation',extractionMethod:'explicit'},evidence:[{id:createId(),source:'conversation',quote:correction,createdAt:now()}],relatedEntities:[...target.relatedEntities,{entityId:target.id,type:'corrects'}],createdAt:now(),updatedAt:now(),confirmedAt:undefined,supersededBy:undefined};result={...result,knowledgeEntities:[corrected,...result.knowledgeEntities]};}
  let next=mergeProjectKnowledge(graph,result);const timestamp=now();next={...next,knowledge:{...next.knowledge!,confirmations:next.knowledge!.confirmations.map(item=>item.id===confirmationId?{...item,status:'edited',resolvedAt:timestamp,resolutionNote:correction}:item),updatedAt:timestamp},updatedAt:timestamp};traceConfirmationResolution(confirmationId,'edited');return next;
}

export function getActiveKnowledge(graph:ProjectGraph){return (graph.knowledge?.entities??[]).filter(item=>item.status!=='superseded'&&item.status!=='contradicted'&&item.status!=='not_applicable');}
export function getConfirmedKnowledge(graph:ProjectGraph){return getActiveKnowledge(graph).filter(item=>item.status==='confirmed'||item.status==='validated');}
export function getProposedKnowledge(graph:ProjectGraph){return getActiveKnowledge(graph).filter(item=>item.status==='proposed'||item.status==='detected'||item.status==='unknown');}
export function getPendingConfirmations(graph:ProjectGraph){return (graph.knowledge?.confirmations??[]).filter(item=>item.status==='pending');}
export function getDeferredConfirmations(graph:ProjectGraph){return (graph.knowledge?.confirmations??[]).filter(item=>item.status==='dismissed');}
export function reopenConfirmation(graph:ProjectGraph,confirmationId:string){const base=graph.knowledge??createInitialProjectKnowledgeState(),timestamp=now();return{...graph,knowledge:{...base,confirmations:base.confirmations.map(item=>item.id===confirmationId&&item.status==='dismissed'?{...item,status:'pending' as const,resolvedAt:undefined}:item),updatedAt:timestamp},updatedAt:timestamp};}

export function traceInterpretation(message:string,result:ProjectInterpretationResult){if(process.env.NODE_ENV!=='development')return;console.debug('[ExecutiveEngineV2 interpretation]',{message,entities:result.knowledgeEntities.map(({id,type,key,status,confidence})=>({id,type,key,status,confidence})),confirmations:result.confirmationRequests.map(({intent,impact})=>({intent,impact})),patches:result.modulePatches.map(({moduleId,scoreBoost})=>({moduleId,scoreBoost}))});}
function traceConfirmationResolution(confirmationId:string,status:string){if(process.env.NODE_ENV==='development')console.debug('[ExecutiveEngineV2 confirmation]',{confirmationId,status});}
