'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { Archive, FolderOpen, RotateCcw, Trash2 } from 'lucide-react';
import type { WorkspaceState } from '../types/workspace';

interface Props { workspace: WorkspaceState; onCreateProject: () => void; onOpenProject: (id:string)=>void; onArchiveProject:(id:string)=>void; onRestoreProject:(id:string)=>void; onDeleteProject:(id:string)=>void; }

export function WorkspaceHome({workspace,onCreateProject,onOpenProject,onArchiveProject,onRestoreProject,onDeleteProject}:Props){
  const [filter,setFilter]=useState<'all'|'active'|'archived'>('active');
  const [deleteTarget,setDeleteTarget]=useState<string|null>(null);
  const [confirmation,setConfirmation]=useState('');
  const activeCount=workspace.projects.filter((p)=>p.lifecycleStatus!=='archived').length;
  const projects=useMemo(()=>workspace.projects.filter((p)=>filter==='all'||p.lifecycleStatus===filter),[workspace.projects,filter]);
  return <main className="min-h-screen bg-superficie px-6 py-10 text-texto-largo sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl space-y-10">
    <header className="flex flex-col gap-7 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex gap-3"><Link href="/" className="rounded-full border border-borde/15 px-4 py-2 text-xs text-texto-largo">← Volver al medio</Link><Link href="/mi-ecosistema" className="rounded-full border border-borde/15 px-4 py-2 text-xs text-texto-largo">Mi Ecosistema</Link></div><p className="mt-7 text-sm uppercase tracking-[.25em] text-texto-principal">Portal del Participante</p><h1 className="mt-3 text-4xl font-semibold sm:text-6xl">Hola, {workspace.user?.name||'Productor'}.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-texto-largo">Este es tu centro de producción. Desarrolla cada proyecto con Creative OS, desde la idea hasta el presupuesto, el cronograma y la convocatoria.</p></div><button onClick={onCreateProject} className="rounded-full bg-rojo-base px-6 py-3 font-bold text-hueso">Crear nuevo proyecto</button></header>
    <section className="grid gap-5 md:grid-cols-3"><Metric label="Proyectos activos" value={activeCount}/><Metric label="Archivados" value={workspace.projects.length-activeCount}/><Metric label="Total" value={workspace.projects.length}/></section>
    <section><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase text-texto-largo">Mesas de producción</p><h2 className="mt-2 text-3xl font-semibold">Mis proyectos</h2></div><div className="flex gap-2">{(['all','active','archived'] as const).map((v)=><button key={v} onClick={()=>setFilter(v)} className={`rounded-full px-4 py-2 text-sm ${filter===v?'bg-rojo-base font-bold text-hueso':'border border-borde/15 text-texto-largo'}`}>{v==='all'?'Todos':v==='active'?'Activos':'Archivados'}</button>)}</div></div>
      {!projects.length?<div className="rounded-3xl border border-dashed border-borde/15 p-10"><h3 className="text-2xl font-semibold">{filter==='archived'?'No hay proyectos archivados':'Crea tu primer proyecto'}</h3><p className="mt-3 text-texto-largo">{filter==='archived'?'Los proyectos que archives aparecerán aquí y podrás restaurarlos.':'Creative OS abrirá una Mesa de Producción conectada a todas tus herramientas.'}</p>{filter!=='archived'?<button onClick={onCreateProject} className="mt-6 rounded-full bg-rojo-base px-5 py-2 font-bold text-hueso">Nuevo proyecto</button>:null}</div>:<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{projects.map((project)=><article key={project.id} className="rounded-3xl border border-borde/10 bg-superficie-elevada p-6"><div className="flex justify-between"><p className="text-xs uppercase text-texto-largo">{project.category}</p>{project.lifecycleStatus==='archived'?<span className="rounded-full bg-borde/5 px-3 py-1 text-xs text-texto-largo">Archivado</span>:null}</div><h3 className="mt-3 text-2xl font-semibold">{project.title}</h3><p className="mt-3 line-clamp-3 min-h-16 text-sm leading-6 text-texto-largo">{project.description||'Proyecto sin descripción inicial.'}</p><div className="mt-6 flex flex-wrap gap-2"><button onClick={()=>onOpenProject(project.id)} className="inline-flex items-center gap-2 rounded-full bg-rojo-base px-4 py-2 text-sm font-bold text-hueso"><FolderOpen size={15}/> Abrir</button>{project.lifecycleStatus==='archived'?<><button onClick={()=>onRestoreProject(project.id)} className="inline-flex items-center gap-2 rounded-full border border-borde/15 px-4 py-2 text-sm"><RotateCcw size={15}/> Restaurar</button><button onClick={()=>{setDeleteTarget(project.id);setConfirmation('')}} className="rounded-full border border-borde p-2 text-rojo-base" title="Eliminar definitivamente"><Trash2 size={16}/></button></>:<button onClick={()=>onArchiveProject(project.id)} className="inline-flex items-center gap-2 rounded-full border border-borde/15 px-4 py-2 text-sm text-texto-largo"><Archive size={15}/> Archivar</button>}</div></article>)}</div>}
    </section>
    <section className="grid gap-5 md:grid-cols-2"><Link href="/#historias" className="rounded-3xl border border-borde/10 bg-superficie-elevada p-7"><p className="text-xs uppercase text-texto-largo">Medio</p><h3 className="mt-3 text-2xl font-semibold">Inspiración y legitimación</h3><p className="mt-3 text-sm leading-6 text-texto-largo">Explora historias, espacios y procesos culturales destacados.</p></Link><Link href="/ecosistema" className="rounded-3xl border border-borde/10 bg-superficie-elevada p-7"><p className="text-xs uppercase text-texto-largo">Ecosistema</p><h3 className="mt-3 text-2xl font-semibold">Personas y conexiones</h3><p className="mt-3 text-sm leading-6 text-texto-largo">Encuentra actores que pueden fortalecer tus proyectos.</p></Link></section>
  </div>{deleteTarget?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-6"><section className="w-full max-w-lg rounded-3xl border border-borde bg-superficie-elevada p-7"><p className="text-xs uppercase tracking-wider text-rojo-base">Segunda confirmación</p><h2 className="mt-3 text-2xl font-semibold">Eliminar definitivamente</h2><p className="mt-4 leading-7 text-texto-largo">Se eliminarán el proyecto, sus conversaciones, documentos, presupuesto, cronograma y todos los datos relacionados. Esta acción no se puede deshacer.</p><label className="mt-6 block text-sm">Escribe <strong>ELIMINAR</strong><input autoFocus value={confirmation} onChange={(e)=>setConfirmation(e.target.value)} className="mt-2 w-full rounded-xl border border-borde/15 bg-superficie-elevada p-3"/></label><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setDeleteTarget(null)} className="rounded-full border border-borde/15 px-5 py-2">Cancelar</button><button disabled={confirmation!=='ELIMINAR'} onClick={()=>{if(confirmation==='ELIMINAR'){onDeleteProject(deleteTarget);setDeleteTarget(null)}}} className="rounded-full bg-rojo-base px-5 py-2 font-bold text-hueso disabled:opacity-30">Sí, eliminar</button></div></section></div>:null}</main>;
}
function Metric({label,value}:{label:string;value:number}){return <article className="rounded-3xl border border-borde/10 bg-superficie-elevada p-6"><p className="text-xs uppercase text-texto-largo">{label}</p><strong className="mt-3 block text-4xl text-texto-principal">{value}</strong></article>}
