-- Entrada unificada, decisiones independientes y auditoría. Ejecutar después de 032.
begin;
alter table public.project_applications add column if not exists source_type text not null default 'creative_os' check(source_type in('creative_os','imported_project','public_application'));
alter table public.project_applications add column if not exists files jsonb not null default '[]'::jsonb;
alter table public.project_applications add column if not exists ecosystem_accepted_at timestamptz;
alter table public.project_applications add column if not exists agenda_status text not null default 'not_requested' check(agenda_status in('not_requested','pending_data','approved','published','rejected'));
alter table public.project_applications add column if not exists editorial_status text not null default 'not_requested' check(editorial_status in('not_requested','referred','in_review','published','not_selected'));
alter table public.project_applications add column if not exists experience_id uuid references public.experiences(id) on delete set null;
create table if not exists public.project_reanalysis_audits(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,requested_by uuid not null default auth.uid() references public.profiles(id),differences jsonb not null default '[]',accepted_differences jsonb not null default '[]',created_at timestamptz not null default now(),accepted_at timestamptz);
alter table public.project_reanalysis_audits enable row level security;
create policy "Owners manage reanalysis audits" on public.project_reanalysis_audits for all to authenticated using(exists(select 1 from public.projects p where p.id=project_id and p.owner_id=auth.uid())) with check(exists(select 1 from public.projects p where p.id=project_id and p.owner_id=auth.uid()));
grant select,insert,update on public.project_reanalysis_audits to authenticated;
create or replace function public.approve_application_for_agenda(target_application_id uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare a public.project_applications%rowtype; eid uuid; start_at timestamptz; begin if public.current_profile_role() not in('ecosystem_admin','super_admin') then raise exception 'No tienes permiso'; end if; select * into a from public.project_applications where id=target_application_id; if a.status<>'accepted' then raise exception 'Primero acepta el proyecto dentro del ecosistema'; end if; if a.application_type not in('experience','activation') then raise exception 'El proyecto no corresponde a una actividad de agenda'; end if; start_at:=nullif(a.experience_details->>'startsAt','')::timestamptz; if start_at is null then update public.project_applications set agenda_status='pending_data' where id=a.id; raise exception 'Completa los datos operativos antes de aprobar para agenda'; end if; insert into public.experiences(owner_id,project_id,title,summary,description,experience_type,city,venue_name,starts_at,ends_at,capacity,ticket_url,cover_image_url,status) values(a.applicant_profile_id,a.project_id,coalesce(nullif(a.experience_details->>'experienceName',''),a.snapshot->>'projectTitle'),a.public_summary,a.snapshot->>'projectDescription',coalesce(nullif(a.experience_details->>'experienceType',''),'event'),a.geographic_scope,a.experience_details->>'venueName',start_at,nullif(a.experience_details->>'endsAt','')::timestamptz,nullif(a.experience_details->>'expectedParticipants','')::integer,a.experience_details->>'registrationUrl',a.experience_details->>'coverImageUrl','draft') returning id into eid; update public.project_applications set agenda_status='approved',experience_id=eid where id=a.id; return eid; end $$;
revoke all on function public.approve_application_for_agenda(uuid) from public; grant execute on function public.approve_application_for_agenda(uuid) to authenticated;
commit;
