import 'server-only';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { appendFile, mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises';
import type { EmbeddingProvider, KnowledgeIndex, KnowledgeSearchQuery, KnowledgeSearchResult, KnowledgeSource } from '../../types/knowledge';
import { KNOWLEDGE_CACHE_PATH,KNOWLEDGE_INDEX_PATH,KNOWLEDGE_LIBRARY_PATH,KNOWLEDGE_LOG_PATH,PARSER_VERSION,SUPPORTED_EXTENSIONS } from './knowledgeConfig';
import { parseKnowledgeDocument } from './documentParsers';
import { chunkDocument } from './knowledgeChunker';
import { categorize,keywords,normalize } from './knowledgeTaxonomy';

const EMPTY:KnowledgeIndex={version:1,generatedAt:new Date(0).toISOString(),documents:[],chunks:[],failures:[]};
export class KnowledgeEngine{
 private index:KnowledgeIndex=EMPTY; private initialized=false; private initializing:Promise<void>|null=null;
 constructor(private embeddings:EmbeddingProvider|null=null){}
 async initialize(){if(this.initialized)return;if(this.initializing)return this.initializing;this.initializing=this.refresh().then(()=>{this.initialized=true}).finally(()=>{this.initializing=null});return this.initializing;}
 async refresh(){await mkdir(KNOWLEDGE_CACHE_PATH,{recursive:true});this.index=await this.loadIndex();const files=await scan(KNOWLEDGE_LIBRARY_PATH);const catalog=await loadCatalog();const activePaths=new Set(files.map(f=>relative(f)));
  const nextDocs=this.index.documents.filter(d=>activePaths.has(d.file));const nextChunks=this.index.chunks.filter(c=>nextDocs.some(d=>d.id===c.documentId));const failures=this.index.failures.filter(f=>activePaths.has(f.file));
  for(const file of files){const rel=relative(file);const buffer=await readFile(file);const checksum=createHash('sha256').update(buffer).digest('hex');const previous=nextDocs.find(d=>d.file===rel);if(previous?.checksum===checksum&&previous.version===PARSER_VERSION)continue;try{const extracted=await parseKnowledgeDocument(file);const row=catalog.find(c=>normalize(c.titulo??'')===normalize(path.basename(file,path.extname(file)).replaceAll('_',' ')))??catalog.find(c=>normalize(path.basename(file)).includes(normalize((c.titulo??'').split(' ').slice(0,3).join(' '))));const now=new Date().toISOString();const id=previous?.id??createHash('sha256').update(rel).digest('hex').slice(0,32);const combined=extracted.pages.map(p=>p.text).join(' ');const topics=[...new Set([row?.tema,...categorize(combined)].flat().filter((x):x is string=>Boolean(x)))];const doc:KnowledgeSource={id,title:extracted.title||row?.titulo||path.basename(file,path.extname(file)).replaceAll('_',' '),author:extracted.author||null,institution:row?.institucion||'Creative OS',year:yearOf(row?.titulo||file),language:language(row?.idioma),topic:topics[0]||'Creative OS',subcategory:topics.slice(1),license:row?.licencia_o_condicion||'Uso interno pendiente de revisión',source:row?.tipo||'biblioteca_local',url:row?.url||'',file:rel,checksum,createdAt:previous?.createdAt??now,updatedAt:now,status:'active',publicationDate:null,jurisdiction:'CO',sourceType:row?.tipo||'local',canonicalUrl:row?.url||`library://${rel.replaceAll('\\','/')}`,retrievedAt:now,version:PARSER_VERSION,isActive:true};
    const position=nextDocs.findIndex(d=>d.file===rel);if(position>=0)nextDocs[position]=doc;else nextDocs.push(doc);for(let i=nextChunks.length-1;i>=0;i--)if(nextChunks[i].documentId===id)nextChunks.splice(i,1);const chunks=chunkDocument(id,extracted.pages,doc.jurisdiction);if(this.embeddings)for(const chunk of chunks)chunk.embedding=await this.embeddings.embed(chunk.text);nextChunks.push(...chunks);
  }catch(error){for(let i=failures.length-1;i>=0;i--)if(failures[i].file===rel)failures.splice(i,1);failures.push({file:rel,message:error instanceof Error?error.message:String(error),updatedAt:new Date().toISOString()});}}
  this.index={version:1,generatedAt:new Date().toISOString(),documents:nextDocs,chunks:nextChunks,failures:failures.filter(f=>!nextDocs.some(d=>d.file===f.file))};await this.persist();
 }
 async search(query:KnowledgeSearchQuery):Promise<KnowledgeSearchResult[]>{await this.initialize();const q=normalize(query.text);const qWords=new Set(keywords(q,30));const topicSet=new Set((query.topics??categorize(q)).map(normalize));const scored:KnowledgeSearchResult[]=[];for(const chunk of this.index.chunks){const source=this.index.documents.find(d=>d.id===chunk.documentId);if(!source||source.status!=='active')continue;let score=0;const matchedBy:KnowledgeSearchResult['matchedBy']=[];const metadata=normalize([source.title,source.institution,source.topic,...source.subcategory,...chunk.topics].join(' '));const metadataHits=[...topicSet].filter(t=>metadata.includes(t)).length;if(metadataHits){score+=metadataHits*5;matchedBy.push('metadata');}const keywordHits=chunk.keywords.filter(k=>qWords.has(normalize(k))).length;if(keywordHits){score+=keywordHits*2;matchedBy.push('keywords');}if(q.length>5&&normalize(chunk.text).includes(q)){score+=8;if(!matchedBy.includes('keywords'))matchedBy.push('keywords');}if(query.embedding&&chunk.embedding?.length===query.embedding.length){score+=cosine(query.embedding,chunk.embedding)*10;matchedBy.push('embedding');}if(score>0)scored.push({chunk,source,score,matchedBy});}const results=scored.sort((a,b)=>b.score-a.score).slice(0,query.limit??5);await this.log(query,results);return results;}
 getStats(){return{documents:this.index.documents.length,chunks:this.index.chunks.length,failures:this.index.failures.length,generatedAt:this.index.generatedAt,libraryPath:KNOWLEDGE_LIBRARY_PATH};}
 private async loadIndex(){try{return JSON.parse(await readFile(KNOWLEDGE_INDEX_PATH,'utf8')) as KnowledgeIndex}catch{return EMPTY}}
 private async persist(){await writeFile(KNOWLEDGE_INDEX_PATH,JSON.stringify(this.index,null,2),'utf8')}
 private async log(query:KnowledgeSearchQuery,results:KnowledgeSearchResult[]){const record={query:query.text,topic:(query.topics??categorize(query.text)).join(', '),sourceIds:[...new Set(results.map(r=>r.source.id))],chunkIds:results.map(r=>r.chunk.id),projectId:query.projectId??null,purpose:query.purpose,createdAt:new Date().toISOString()};await appendFile(KNOWLEDGE_LOG_PATH,`${JSON.stringify(record)}\n`,'utf8')}
}
async function scan(root:string):Promise<string[]>{const out:string[]=[];for(const entry of await readdir(root,{withFileTypes:true})){if(entry.name==='.knowledge-cache')continue;const full=path.join(root,entry.name);if(entry.isDirectory())out.push(...await scan(full));else if(SUPPORTED_EXTENSIONS.has(path.extname(entry.name).toLowerCase()))out.push(full);}return out;}
const relative=(file:string)=>path.relative(KNOWLEDGE_LIBRARY_PATH,file);
async function loadCatalog():Promise<Record<string,string>[]> {try{const text=await readFile(path.join(KNOWLEDGE_LIBRARY_PATH,'05_catalogo','catalogo_recursos.csv'),'utf8');const [header,...rows]=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean).map(parseCsv);return rows.map(row=>Object.fromEntries(header.map((key,i)=>[key,row[i]??''])))}catch{return[]}}
function parseCsv(line:string){const out:string[]=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){value+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){out.push(value);value='';}else value+=c;}out.push(value);return out;}
const yearOf=(v:string)=>Number(v.match(/\b(19|20)\d{2}\b/)?.[0]??0)||null;const language=(v?:string)=>normalize(v??'').startsWith('ingl')?'en':'es';
function cosine(a:number[],b:number[]){let dot=0,aa=0,bb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]**2;bb+=b[i]**2;}return dot/(Math.sqrt(aa)*Math.sqrt(bb)||1)}
export const knowledgeEngine=new KnowledgeEngine();
