import path from 'node:path';
export const KNOWLEDGE_LIBRARY_PATH=path.join(process.cwd(),'biblioteca_creative_os');
export const KNOWLEDGE_CACHE_PATH=path.join(KNOWLEDGE_LIBRARY_PATH,'.knowledge-cache');
export const KNOWLEDGE_INDEX_PATH=path.join(KNOWLEDGE_CACHE_PATH,'index.json');
export const KNOWLEDGE_LOG_PATH=path.join(KNOWLEDGE_CACHE_PATH,'retrieval-log.ndjson');
export const KNOWLEDGE_INGESTION_LOG_PATH=path.join(KNOWLEDGE_CACHE_PATH,'ingestion-log.ndjson');
export const KNOWLEDGE_REPORT_PATH=path.join(KNOWLEDGE_CACHE_PATH,'ingestion-report.json');
export const SUPPORTED_EXTENSIONS=new Set(['.pdf','.md','.markdown','.txt','.docx','.html','.htm']);
export const ADMIN_EXTENSIONS=new Set(['.csv','.json']);
export const PARSER_VERSION='knowledge-engine-3';
export const COGNITIVE_COLLECTION_ID='creative_os_cognitive_research_cases';
