import path from 'node:path';
import { createHash } from 'node:crypto';
import { appendFile,mkdir,readFile,readdir,stat,writeFile } from 'node:fs/promises';
import type { EmbeddingProvider,KnowledgeIndex,KnowledgeIngestionEvent,KnowledgeIngestionReport,KnowledgeSearchQuery,KnowledgeSearchResult,KnowledgeSource } from '../../types/knowledge';
import { KNOWLEDGE_CACHE_PATH,KNOWLEDGE_INDEX_PATH,KNOWLEDGE_INGESTION_LOG_PATH,KNOWLEDGE_LIBRARY_PATH,KNOWLEDGE_LOG_PATH,KNOWLEDGE_REPORT_PATH,PARSER_VERSION,SUPPORTED_EXTENSIONS } from './knowledgeConfig';
import { parseKnowledgeDocument } from './documentParsers';
import { chunkDocument } from './knowledgeChunker';
import { categorize,keywords,normalize } from './knowledgeTaxonomy';
import { DEFAULT_COLLECTION_ID,findCatalogRecord,loadKnowledgeCatalogs,type CatalogRecord } from './knowledgeCatalog';

const EMPTY:KnowledgeIndex={version:2,generatedAt:new Date(0).toISOString(),documents:[],chunks:[],failures:[]};
export class KnowledgeEngine{
 private index:KnowledgeIndex=EMPTY;private initialized=false;private initializing:Promise<void>|null=null;
 constructor(private embeddings:EmbeddingProvider|null=null){}
 async initialize(){if(this.initialized)return;if(this.initializing)return this.initializing;this.initializing=(async()=>{await mkdir(KNOWLEDGE_CACHE_PATH,{recursive:true});this.index=await this.loadIndex();if(!this.index.documents.length)await this.refresh();this.initialized=true;})().finally(()=>{this.initializing=null});return this.initializing;}
 async discover(){const catalog=await loadKnowledgeCatalogs();const allFiles=await scanAll(KNOWLEDGE_LIBRARY_PATH);const narrative=allFiles.filter(file=>SUPPORTED_EXTENSIONS.has(path.extname(file).toLowerCase())&&!catalog.administrativeFiles.has(relative(file)));return{totalFiles:allFiles.length,narrativeFiles:narrative.map(relative),administrativeFiles:[...catalog.administrativeFiles],catalogSources:catalog.records.length,externalMetadataOnly:catalog.records.filter(record=>!record.file).length,warnings:catalog.warnings};}
 async refresh(){
  const started=Date.now();await mkdir(KNOWLEDGE_CACHE_PATH,{recursive:true});this.index=await this.loadIndex();const catalog=await loadKnowledgeCatalogs();const allFiles=await scanAll(KNOWLEDGE_LIBRARY_PATH);const files=allFiles.filter(file=>SUPPORTED_EXTENSIONS.has(path.extname(file).toLowerCase())&&!catalog.administrativeFiles.has(relative(file)));const activePaths=new Set(files.map(relative));
  const nextDocs=this.index.documents.map(document=>activePaths.has(normalizePath(document.filePath||document.file))?document:{...document,status:'missing' as const,isActive:false,processingStatus:'metadata_registered' as const,updatedAt:new Date().toISOString()});
  const nextChunks=[...this.index.chunks];const failures=[...this.index.failures];const events:KnowledgeIngestionEvent[]=[];const metadataWarnings=[...catalog.warnings];const licenseWarnings:string[]=[];let sourcesCreated=0,sourcesUpdated=0,chunksCreated=0,chunksReplaced=0,pagesProcessed=0,duplicates=0,skipped=0,failed=0;
  const canonicalByKey=new Map<string,KnowledgeSource>();for(const document of nextDocs)for(const key of duplicateKeys(document))if(key)canonicalByKey.set(key,document);
  for(const file of files){const fileStarted=Date.now();const rel=relative(file);const buffer=await readFile(file);const checksum=createHash('sha256').update(buffer).digest('hex');const fileStat=await stat(file);const previous=nextDocs.find(document=>normalizePath(document.filePath||document.file)===rel);const record=findCatalogRecord(catalog.records,rel);
    if(previous?.checksum===checksum&&previous.version===PARSER_VERSION&&previous.processingStatus==='indexed'){skipped++;events.push(event(rel,checksum,'indexed',0,0,previous.pageCount??0,Date.now()-fileStarted,'Sin cambios; omitido incrementalmente.'));continue;}
    try{
      const duplicate=findDuplicate(canonicalByKey,checksum,record,rel,previous?.id);
      if(duplicate){duplicates++;skipped++;if(!duplicate.collectionIds.includes(record?.collectionId??DEFAULT_COLLECTION_ID)){duplicate.collectionIds.push(record?.collectionId??DEFAULT_COLLECTION_ID);duplicate.updatedAt=new Date().toISOString();}events.push(event(rel,checksum,'skipped_duplicate',0,0,0,Date.now()-fileStarted,`Fuente canónica: ${duplicate.filePath}`));continue;}
      const extracted=await parseKnowledgeDocument(file);const now=new Date().toISOString();const id=previous&&isUuid(previous.id)?previous.id:stableId(record?.url||rel);const combined=extracted.pages.map(page=>page.text).join(' ');const topics=[...new Set([...(record?.topics??[]),...categorize(combined)])];const collectionId=record?.collectionId??DEFAULT_COLLECTION_ID;const doc=buildSource({id,rel,checksum,fileSize:fileStat.size,record,extracted,topics,previous,now});
      const existingPosition=nextDocs.findIndex(document=>document.id===id);if(existingPosition>=0){nextDocs[existingPosition]=doc;sourcesUpdated++;}else{nextDocs.push(doc);sourcesCreated++;}
      const oldChunkCount=nextChunks.filter(chunk=>chunk.documentId===id).length;for(let index=nextChunks.length-1;index>=0;index--)if(nextChunks[index].documentId===id)nextChunks.splice(index,1);chunksReplaced+=oldChunkCount;
      const chunks=chunkDocument(id,extracted.pages,{collectionId,jurisdiction:doc.jurisdiction,language:doc.language,sourceTopics:topics,sourceType:doc.sourceType});if(!chunks.length)throw new Error('El documento fue parseado pero no produjo chunks utilizables.');
      if(this.embeddings)for(const chunk of chunks)chunk.embedding=await this.embeddings.embed(chunk.text);nextChunks.push(...chunks);chunksCreated+=chunks.length;pagesProcessed+=extracted.pageCount??extracted.pages.length;doc.processingStatus='indexed';doc.indexedAt=now;doc.pageCount=extracted.pageCount??extracted.pages.length;doc.metadata={...doc.metadata,parserWarnings:extracted.warnings};for(const key of duplicateKeys(doc))if(key)canonicalByKey.set(key,doc);
      failures.splice(0,failures.length,...failures.filter(failure=>failure.file!==rel));events.push(event(rel,checksum,'indexed',chunks.length,oldChunkCount,extracted.pageCount??extracted.pages.length,Date.now()-fileStarted));
      if(!record)metadataWarnings.push(`${rel}: no tiene entrada explícita de catálogo.`);if(/verify|consult|pendiente|revisi/i.test(doc.license))licenseWarnings.push(`${rel}: ${doc.license}`);
    }catch(error){failed++;const errorMessage=message(error);const old=nextDocs.find(document=>(document.filePath||document.file)===rel);if(old){old.status='error';old.processingStatus='failed';old.processingError=errorMessage;old.updatedAt=new Date().toISOString();}failures.splice(0,failures.length,...failures.filter(failure=>failure.file!==rel),{file:rel,message:errorMessage,updatedAt:new Date().toISOString()});events.push(event(rel,checksum,'failed',0,0,0,Date.now()-fileStarted,errorMessage));}
  }
  registerMetadataOnlySources(nextDocs,catalog.records,canonicalByKey,metadataWarnings);
  for(let index=nextDocs.length-1;index>=0;index--){const source=nextDocs[index];if(source.processingStatus!=='metadata_registered'||!source.canonicalUrl)continue;const canonical=nextDocs.find(candidate=>candidate.id!==source.id&&candidate.isActive&&normalizeUrl(candidate.canonicalUrl)===normalizeUrl(source.canonicalUrl));if(canonical){canonical.collectionIds=[...new Set([...canonical.collectionIds,...source.collectionIds])];nextDocs.splice(index,1);}}
  for(let index=nextDocs.length-1;index>=0;index--){const source=nextDocs[index];if(!source.checksum)continue;const canonical=nextDocs.find(candidate=>candidate.id!==source.id&&candidate.checksum===source.checksum&&candidate.isActive&&isUuid(candidate.id));if(!canonical)continue;canonical.collectionIds=[...new Set([...canonical.collectionIds,...source.collectionIds])];for(let chunkIndex=nextChunks.length-1;chunkIndex>=0;chunkIndex--)if(nextChunks[chunkIndex].sourceId===source.id)nextChunks.splice(chunkIndex,1);nextDocs.splice(index,1);}
  const byFormat=Object.fromEntries([...new Set(allFiles.map(file=>path.extname(file).toLowerCase()||'[none]'))].sort().map(ext=>[ext,allFiles.filter(file=>(path.extname(file).toLowerCase()||'[none]')===ext).length]));
  const report:KnowledgeIngestionReport={generatedAt:new Date().toISOString(),totalFiles:allFiles.length,byFormat,processed:events.filter(item=>item.result==='indexed'&&!item.message?.startsWith('Sin cambios')).length,skipped,duplicates,failed,sourcesCreated,sourcesUpdated,chunksCreated,chunksReplaced,pagesProcessed,errors:events.filter(item=>item.result==='failed').map(item=>({file:item.file,message:item.message??'Error desconocido'})),metadataWarnings:[...new Set(metadataWarnings)],licenseWarnings:[...new Set(licenseWarnings)],events};
  this.index={version:2,generatedAt:report.generatedAt,documents:nextDocs,chunks:nextChunks,failures,ingestionReport:report};await this.persist();await appendEvents(events);await writeFile(KNOWLEDGE_REPORT_PATH,JSON.stringify({...report,durationMs:Date.now()-started},null,2),'utf8');return report;
 }
 async search(query:KnowledgeSearchQuery):Promise<KnowledgeSearchResult[]>{await this.initialize();const q=normalize(query.text);const qWords=new Set(keywords(q,30));const topicSet=new Set((query.topics??categorize(q)).map(normalize));const collectionSet=new Set(query.collectionIds??[]);const scored:KnowledgeSearchResult[]=[];for(const chunk of this.index.chunks){const source=this.index.documents.find(document=>document.id===chunk.documentId);if(!source||source.status!=='active'||!source.isActive)continue;if(collectionSet.size&&!collectionSet.has(chunk.collectionId)&&!source.collectionIds.some(id=>collectionSet.has(id)))continue;let score=0;const matchedBy:KnowledgeSearchResult['matchedBy']=[];const metadata=normalize([source.title,source.institution,source.topic,...source.topics,...chunk.topics,...chunk.reasoningModes,...chunk.headingPath].join(' '));const metadataHits=[...topicSet].filter(topic=>metadata.includes(topic)).length;if(metadataHits){score+=metadataHits*5;matchedBy.push('metadata');}const keywordHits=chunk.keywords.filter(keyword=>qWords.has(normalize(keyword))).length;if(keywordHits){score+=keywordHits*2;matchedBy.push('keywords');}if(q.length>5&&normalize(chunk.text).includes(q)){score+=8;if(!matchedBy.includes('keywords'))matchedBy.push('keywords');}const contextual=scoreContext(chunk,query);if(contextual){score+=contextual;matchedBy.push('context');}if(query.embedding&&chunk.embedding?.length===query.embedding.length){score+=cosine(query.embedding,chunk.embedding)*10;matchedBy.push('embedding');}if(score>0)scored.push({chunk,source,score,matchedBy});}const results=scored.sort((a,b)=>b.score-a.score).slice(0,query.limit??5);await this.log(query,results);return results;}
 getStats(){return{documents:this.index.documents.filter(document=>document.isActive).length,chunks:this.index.chunks.length,failures:this.index.failures.length,generatedAt:this.index.generatedAt,libraryPath:KNOWLEDGE_LIBRARY_PATH,collections:Object.fromEntries([...new Set(this.index.documents.flatMap(document=>document.collectionIds))].map(id=>[id,this.index.documents.filter(document=>document.collectionIds.includes(id)&&document.isActive).length]))};}
 getReport(){return this.index.ingestionReport??null;}
 getIndexSnapshot(){return structuredClone(this.index);}
 private async loadIndex(){try{return migrateIndex(JSON.parse(await readFile(KNOWLEDGE_INDEX_PATH,'utf8')) as KnowledgeIndex)}catch{return structuredClone(EMPTY);}}
 private async persist(){await writeFile(KNOWLEDGE_INDEX_PATH,JSON.stringify(this.index,null,2),'utf8');}
 private async log(query:KnowledgeSearchQuery,results:KnowledgeSearchResult[]){const record={query:query.text,topic:(query.topics??categorize(query.text)).join(', '),sourceIds:[...new Set(results.map(result=>result.source.id))],chunkIds:results.map(result=>result.chunk.id),projectId:query.projectId??null,purpose:query.purpose,createdAt:new Date().toISOString()};await appendFile(KNOWLEDGE_LOG_PATH,`${JSON.stringify(record)}\n`,'utf8');}
}

function buildSource(input:{id:string;rel:string;checksum:string;fileSize:number;record?:CatalogRecord;extracted:Awaited<ReturnType<typeof parseKnowledgeDocument>>;topics:string[];previous?:KnowledgeSource;now:string}):KnowledgeSource{const {id,rel,checksum,fileSize,record,extracted,topics,previous,now}=input;const fileName=path.basename(rel);const collectionId=record?.collectionId??DEFAULT_COLLECTION_ID;const title=record?.title||extracted.title||path.basename(fileName,path.extname(fileName)).replace(/^\d+_/,'').replaceAll('_',' ');const year=record?.year??yearOf(title);return{id,collectionId,collectionIds:[...new Set([...(previous?.collectionIds??[]),collectionId])],filePath:rel,fileName,fileSize,pageCount:extracted.pageCount,title,author:extracted.author||record?.author||null,institution:record?.institution||'Creative OS',year,publicationYear:year,language:record?.language||languageFromContent(extracted.pages.map(page=>page.text).join(' ').slice(0,3000)),documentType:record?.documentType||path.extname(fileName).slice(1),topic:topics[0]||'Creative OS',topics,subcategory:topics.slice(1),license:record?.license||'Uso interno pendiente de revisión',source:record?.sourceType||'biblioteca_local',sourceType:record?.sourceType||'local',url:record?.url||'',canonicalUrl:record?.url||`library://${rel.replaceAll('\\','/')}`,checksum,processingStatus:'parsed',processingError:null,createdAt:previous?.createdAt??now,updatedAt:now,indexedAt:null,retrievedAt:now,publicationDate:null,jurisdiction:record?.jurisdiction||'CO',version:PARSER_VERSION,status:'active',isActive:true,metadata:record?.metadata??{},file:rel};}
function registerMetadataOnlySources(documents:KnowledgeSource[],records:CatalogRecord[],canonical:Map<string,KnowledgeSource>,warnings:string[]){for(const record of records.filter(item=>!item.file&&item.metadata.includedInLibrary!==true)){const key=`url:${normalizeUrl(record.url??'')}`;if(!record.url||canonical.has(key))continue;const now=new Date().toISOString();const id=stableId(record.url);const source:KnowledgeSource={id,collectionId:record.collectionId,collectionIds:[record.collectionId],filePath:'',fileName:'',fileSize:0,pageCount:null,title:record.title,author:record.author??null,institution:record.institution??'',year:record.year??null,publicationYear:record.year??null,language:record.language??'en',documentType:'external_reference',topic:record.topics[0]??'Research',topics:record.topics,subcategory:record.topics.slice(1),license:record.license??'License pending verification',source:'catalog_reference',sourceType:'external_reference',url:record.url,canonicalUrl:record.url,checksum:'',processingStatus:'metadata_registered',processingError:null,createdAt:now,updatedAt:now,indexedAt:null,retrievedAt:now,publicationDate:null,jurisdiction:record.jurisdiction??'global',version:PARSER_VERSION,status:'inactive',isActive:false,metadata:record.metadata,file:''};documents.push(source);canonical.set(key,source);warnings.push(`${record.title}: registrada como metadata; archivo no incluido.`);}}
function findDuplicate(canonical:Map<string,KnowledgeSource>,checksum:string,record:CatalogRecord|undefined,rel:string,currentId?:string){const candidates=[`checksum:${checksum}`,record?.url?`url:${normalizeUrl(record.url)}`:'',record?`title:${normalize(`${record.title}|${record.institution??''}|${record.year??''}`)}`:''].filter(Boolean);for(const key of candidates){const found=canonical.get(key);if(found&&!found.filePath&&!found.file)continue;if(found&&found.id!==currentId&&normalizePath(found.filePath||found.file)!==rel)return found;}return undefined;}
function duplicateKeys(source:KnowledgeSource){return[source.checksum?`checksum:${source.checksum}`:'',source.canonicalUrl&&!source.canonicalUrl.startsWith('library://')?`url:${normalizeUrl(source.canonicalUrl)}`:'',`title:${normalize(`${source.title}|${source.institution}|${source.year??''}`)}`];}
function scoreContext(chunk:KnowledgeIndex['chunks'][number],query:KnowledgeSearchQuery){let score=0;score+=(query.reasoningModes??[]).filter(mode=>chunk.reasoningModes.includes(mode)).length*6;score+=(query.projectTypes??[]).filter(type=>chunk.projectTypes.includes(type)).length*3;score+=(query.projectStages??[]).filter(stage=>chunk.projectStages.includes(stage)).length*3;score+=(query.decisionContexts??[]).filter(context=>chunk.decisionContexts.includes(context)).length*4;return score;}
function migrateIndex(index:KnowledgeIndex):KnowledgeIndex{return{...index,version:2,documents:(index.documents??[]).map(document=>({...document,collectionId:document.collectionId??DEFAULT_COLLECTION_ID,collectionIds:document.collectionIds??[document.collectionId??DEFAULT_COLLECTION_ID],filePath:normalizePath(document.filePath??document.file),file:normalizePath(document.file??document.filePath),fileName:document.fileName??path.basename(document.file??''),fileSize:document.fileSize??0,pageCount:document.pageCount??null,publicationYear:document.publicationYear??document.year,documentType:document.documentType??path.extname(document.file??'').slice(1),topics:document.topics??[document.topic,...(document.subcategory??[])].filter(Boolean),processingStatus:document.processingStatus??'indexed',processingError:document.processingError??null,indexedAt:document.indexedAt??document.updatedAt,metadata:document.metadata??{}})),chunks:(index.chunks??[]).map(chunk=>({...chunk,collectionId:chunk.collectionId??DEFAULT_COLLECTION_ID,headingPath:chunk.headingPath??[chunk.heading||chunk.section],sectionTitle:chunk.sectionTitle??chunk.section,tokenCount:chunk.tokenCount??chunk.tokens,pageStart:chunk.pageStart??chunk.page,pageEnd:chunk.pageEnd??chunk.page,reasoningModes:chunk.reasoningModes??[],decisionContexts:chunk.decisionContexts??[],jurisdiction:chunk.jurisdiction??chunk.jurisdictions?.[0]??'CO',language:chunk.language??'es',checksum:chunk.checksum??createHash('sha256').update(chunk.content).digest('hex')}))};}
async function scanAll(root:string):Promise<string[]>{const out:string[]=[];for(const entry of await readdir(root,{withFileTypes:true})){if(entry.name==='.knowledge-cache')continue;const full=path.join(root,entry.name);if(entry.isDirectory())out.push(...await scanAll(full));else out.push(full);}return out;}
async function appendEvents(events:KnowledgeIngestionEvent[]){if(events.length)await appendFile(KNOWLEDGE_INGESTION_LOG_PATH,events.map(item=>JSON.stringify(item)).join('\n')+'\n','utf8');}
const relative=(file:string)=>path.relative(KNOWLEDGE_LIBRARY_PATH,file).replaceAll('\\','/');
const normalizePath=(file:string)=>file.replaceAll('\\','/');
const stableId=(value:string)=>asUuid(createHash('sha256').update(value).digest('hex').slice(0,32));
const asUuid=(hex:string)=>`${hex.slice(0,8)}-${hex.slice(8,12)}-5${hex.slice(13,16)}-a${hex.slice(17,20)}-${hex.slice(20,32)}`;
const isUuid=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const yearOf=(value:string)=>Number(value.match(/\b(19|20)\d{2}\b/)?.[0]??0)||null;
const normalizeUrl=(value:string)=>value.trim().replace(/^https?:\/\/(www\.)?/i,'').replace(/\/$/,'').toLowerCase();
const languageFromContent=(value:string)=>/\b(the|and|with|decision|project)\b/i.test(value)?'en':'es';
const message=(error:unknown)=>error instanceof Error?error.message:String(error);
function event(file:string,checksum:string,result:KnowledgeIngestionEvent['result'],chunks:number,replacedChunks:number,pages:number,durationMs:number,messageText?:string):KnowledgeIngestionEvent{return{file,checksum,result,chunks,replacedChunks,pages,durationMs,message:messageText,createdAt:new Date().toISOString()};}
function cosine(a:number[],b:number[]){let dot=0,aa=0,bb=0;for(let index=0;index<a.length;index++){dot+=a[index]*b[index];aa+=a[index]**2;bb+=b[index]**2;}return dot/(Math.sqrt(aa)*Math.sqrt(bb)||1);}
export const knowledgeEngine=new KnowledgeEngine();
