'use client';

import { CalendarDays, ChevronLeft, ChevronRight, ExternalLink } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

import { supabase } from '@/lib/supabase/client';

interface CalendarEntry { entry_id:string; source:string; title:string; entry_type:string; starts_at:string; ends_at:string|null; status:string; project_id:string|null; experience_id:string|null; city:string|null; actor_name:string; is_own:boolean; }
interface ProjectOption{id:string;title:string}
type View = 'month'|'week'|'list'|'quarter';

export function MasterCalendar({projects}:{projects:ProjectOption[]}) {
  const [anchor,setAnchor]=useState(new Date()); const [view,setView]=useState<View>('month');
  const [entries,setEntries]=useState<CalendarEntry[]>([]); const [source,setSource]=useState('all'); const [status,setStatus]=useState('all'); const [message,setMessage]=useState('');const[open,setOpen]=useState(false);const[entryForm,setEntryForm]=useState({projectId:projects[0]?.id??'',title:'',type:'milestone',startsAt:'',visibility:'ecosystem'});
  const range=useMemo(()=>getRange(anchor,view),[anchor,view]);
  useEffect(()=>{ let active=true; supabase.rpc('list_master_calendar',{requested_from:range.from.toISOString(),requested_to:range.to.toISOString()}).then(({data,error})=>{if(!active)return;setMessage(error?.message??'');setEntries((data??[]) as CalendarEntry[])});return()=>{active=false}},[range]);
  const filtered=entries.filter((entry)=>(source==='all'||entry.source===source)&&(status==='all'||entry.status===status));
  const groups=groupByDay(filtered);
  function move(direction:number){const next=new Date(anchor);const amount=view==='week'?7:view==='quarter'?90:view==='list'?30:30;next.setDate(next.getDate()+direction*amount);setAnchor(next)}
  async function createEntry(){const{error}=await supabase.from('project_calendar_entries').insert({project_id:entryForm.projectId,title:entryForm.title,entry_type:entryForm.type,starts_at:new Date(entryForm.startsAt).toISOString(),visibility:entryForm.visibility});setMessage(error?error.message:'Entrada creada.');if(!error){setOpen(false);setAnchor(new Date(entryForm.startsAt))}}
  async function moveEntry(entry:CalendarEntry){if(entry.source!=='project')return;const value=window.prompt('Nueva fecha y hora (AAAA-MM-DDTHH:mm)',entry.starts_at.slice(0,16));if(!value)return;const id=entry.entry_id.replace('project:','');const{error}=await supabase.from('project_calendar_entries').update({starts_at:new Date(value).toISOString()}).eq('id',id);setMessage(error?error.message:'Fecha actualizada.');if(!error)setEntries((c)=>c.map((item)=>item.entry_id===entry.entry_id?{...item,starts_at:new Date(value).toISOString()}:item))}
  async function cancelEntry(entry:CalendarEntry){if(entry.source!=='project')return;const id=entry.entry_id.replace('project:','');const{error}=await supabase.from('project_calendar_entries').update({status:'cancelled'}).eq('id',id);setMessage(error?error.message:'Entrada cancelada.');if(!error)setEntries((c)=>c.map((item)=>item.entry_id===entry.entry_id?{...item,status:'cancelled'}:item))}
  return <section>
    <div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-5"><div className="flex items-center gap-2"><button title="Periodo anterior" onClick={()=>move(-1)} className="icon-action"><ChevronLeft/></button><button title="Periodo siguiente" onClick={()=>move(1)} className="icon-action"><ChevronRight/></button><strong className="ml-2">{range.label}</strong></div><div className="flex border border-white/15">{(['month','week','list','quarter'] as View[]).map((item)=><button key={item} onClick={()=>setView(item)} className={`px-3 py-2 text-sm ${view===item?'bg-[#D9FF00] text-black':'text-[#aaa]'}`}>{labels[item]}</button>)}</div><div className="flex gap-2"><button onClick={()=>setOpen(!open)} className="bg-[#D9FF00] px-4 py-2 text-sm font-bold text-black">Crear hito</button><Link href="/gestion-agenda" className="inline-flex items-center gap-2 bg-white px-4 py-2 text-sm font-bold text-black">Actividades <ExternalLink size={16}/></Link></div></div>
    {open?<div className="grid gap-3 border-b border-white/10 py-5 md:grid-cols-5"><select value={entryForm.projectId} onChange={(e)=>setEntryForm({...entryForm,projectId:e.target.value})} className="filter">{projects.map((p)=><option key={p.id} value={p.id}>{p.title}</option>)}</select><input value={entryForm.title} onChange={(e)=>setEntryForm({...entryForm,title:e.target.value})} placeholder="Título" className="filter"/><select value={entryForm.type} onChange={(e)=>setEntryForm({...entryForm,type:e.target.value})} className="filter">{['milestone','task','payment','production','delivery','editorial','campaign','ticket_open','ticket_close','deadline'].map((v)=><option key={v}>{v}</option>)}</select><input type="datetime-local" value={entryForm.startsAt} onChange={(e)=>setEntryForm({...entryForm,startsAt:e.target.value})} className="filter"/><button onClick={createEntry} disabled={!entryForm.projectId||!entryForm.title||!entryForm.startsAt} className="bg-white font-bold text-black disabled:opacity-40">Guardar</button></div>:null}
    <div className="flex flex-wrap gap-3 border-b border-white/10 py-4"><Filter value={source} setValue={setSource} options={['all','experience','project','editorial']}/><Filter value={status} setValue={setStatus} options={['all','draft','submitted','published','planned','confirmed','completed','cancelled']}/><span className="ml-auto text-sm text-[#777]">{filtered.length} elementos</span></div>
    {message?<p className="mt-6 border-l-2 border-amber-400 pl-4 text-amber-200">{message}</p>:null}
    <div className="mt-6 grid gap-px bg-white/10 lg:grid-cols-2">{Array.from(groups.entries()).map(([day,items])=><section key={day} className="bg-[#080808] p-5"><h2 className="text-sm font-bold uppercase tracking-[0.16em] text-[#D9FF00]">{formatDay(day)}</h2><div className="mt-4 space-y-2">{items.map((entry)=><article key={entry.entry_id} className="grid grid-cols-[72px_1fr_auto] items-start gap-3 border-t border-white/10 pt-3"><time className="text-sm tabular-nums text-[#888]">{formatTime(entry.starts_at)}</time><div><p className="font-semibold">{entry.title}</p><p className="mt-1 text-xs text-[#777]">{entry.entry_type} · {entry.actor_name}{entry.city?` · ${entry.city}`:''}</p>{entry.source==='project'&&entry.is_own?<div className="mt-2 flex gap-3 text-xs"><button onClick={()=>moveEntry(entry)} className="text-[#D9FF00]">Mover</button><button onClick={()=>cancelEntry(entry)} className="text-red-300">Cancelar</button></div>:null}</div><span className="border border-white/15 px-2 py-1 text-[10px] uppercase text-[#aaa]">{entry.status}</span></article>)}</div></section>)}</div>
    {!message&&!filtered.length?<div className="py-20 text-center"><CalendarDays className="mx-auto text-[#555]"/><p className="mt-4 text-[#777]">No hay elementos en este periodo.</p></div>:null}
    <style jsx>{`.icon-action{display:inline-flex;width:38px;height:38px;align-items:center;justify-content:center;border:1px solid #292929}.icon-action :global(svg){width:17px}.filter{border:1px solid #292929;background:#0a0a0a;padding:.55rem .75rem;color:white}`}</style>
  </section>;
}
const labels:Record<View,string>={month:'Mes',week:'Semana',list:'Lista',quarter:'Trimestre'};
function Filter({value,setValue,options}:{value:string;setValue:(v:string)=>void;options:string[]}){return <select className="filter" value={value} onChange={(e)=>setValue(e.target.value)}>{options.map((option)=><option key={option}>{option}</option>)}</select>}
function getRange(anchor:Date,view:View){const from=new Date(anchor);from.setHours(0,0,0,0);if(view==='week'){from.setDate(from.getDate()-((from.getDay()+6)%7))}else if(view==='quarter'){from.setMonth(Math.floor(from.getMonth()/3)*3,1)}else{from.setDate(1)}const to=new Date(from);if(view==='week')to.setDate(to.getDate()+7);else if(view==='quarter')to.setMonth(to.getMonth()+3);else to.setMonth(to.getMonth()+1);return{from,to,label:`${from.toLocaleDateString('es-CO',{day:'numeric',month:'long',year:'numeric'})} – ${new Date(to.getTime()-86400000).toLocaleDateString('es-CO',{day:'numeric',month:'long',year:'numeric'})}`}}
function groupByDay(entries:CalendarEntry[]){const map=new Map<string,CalendarEntry[]>();for(const entry of entries){const day=entry.starts_at.slice(0,10);map.set(day,[...(map.get(day)??[]),entry])}return map}
function formatDay(day:string){return new Date(`${day}T12:00:00`).toLocaleDateString('es-CO',{weekday:'long',day:'numeric',month:'long'})} function formatTime(value:string){return new Date(value).toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'})}
