'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { loadEditorialPost, normalizeSlug, saveEditorialPost } from '@/services/editorial/editorialCmsService';
import type { EditorialBodyBlock, EditorialPost, EditorialPostStatus, EditorialPostType } from '@/types/editorial';
import { MediaAssetPicker } from './MediaAssetPicker';

const TYPES: EditorialPostType[]=['news','article','interview','profile','chronicle','review','guide','agenda','featured_project','featured_space','featured_artist','call','opinion','sponsored','other'];
const empty: Partial<EditorialPost>={postType:'article',title:'',slug:'',excerpt:'',bodyBlocks:[],coverImageUrl:'',coverImageAlt:'',coverCaption:'',credits:'',byline:'El Culebreo',category:'',tags:[],location:'',status:'draft',seoTitle:'',seoDescription:'',shareTitle:'',shareDescription:'',shareImageUrl:'',isSponsored:false,sponsorLabel:'',sponsorshipDisclosure:'',publishAt:''};

export function EditorialPostEditor({postId,canPublish}:{postId?:string;canPublish:boolean}){
 const router=useRouter(); const [post,setPost]=useState<Partial<EditorialPost>>(empty); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 const [mediaTarget,setMediaTarget]=useState<{kind:'image'|'video';index?:number}|null>(null);
 useEffect(()=>{if(postId)void loadEditorialPost(postId).then(setPost).catch(e=>setError(e.message));},[postId]);
 const update=<K extends keyof EditorialPost>(key:K,value:EditorialPost[K])=>setPost(p=>({...p,[key]:value}));
 function addBlock(type:EditorialBodyBlock['type']){const id=crypto.randomUUID(); const block:EditorialBodyBlock=type==='image'?{id,type,url:'',alt:'',caption:''}:type==='list'?{id,type,items:['']}:(type==='link'||type==='cta'||type==='video')?{id,type,label:'',url:''}:{id,type,text:''};update('bodyBlocks',[...(post.bodyBlocks??[]),block]);}
 function attachMedia(kind:'image'|'video'){const index=(post.bodyBlocks??[]).length;addBlock(kind);setMediaTarget({kind,index});}
 function changeBlock(index:number,changes:Record<string,unknown>){const blocks=[...(post.bodyBlocks??[])];blocks[index]={...blocks[index],...changes} as EditorialBodyBlock;update('bodyBlocks',blocks);}
 function move(index:number,delta:number){const blocks=[...(post.bodyBlocks??[])];const next=index+delta;if(next<0||next>=blocks.length)return;[blocks[index],blocks[next]]=[blocks[next],blocks[index]];update('bodyBlocks',blocks);}
 async function save(status:EditorialPostStatus){setSaving(true);setError('');setMessage('');try{const saved=await saveEditorialPost({...post,id:postId,title:post.title??'',status,slug:post.slug||normalizeSlug(post.title??'')});setPost(saved);setMessage('Cambios guardados.');if(!postId)router.replace(`/admin/stories/${saved.id}`);router.refresh();}catch(e){setError(e instanceof Error?e.message:'No fue posible guardar.');}finally{setSaving(false);}}
 return <main className="min-h-screen bg-superficie text-texto-largo"><div className="mx-auto max-w-6xl px-6 py-10">
  <div className="flex flex-wrap justify-between gap-5"><div><p className="text-xs font-bold uppercase text-texto-principal">Editor estructurado</p><h1 className="mt-2 text-3xl font-bold">{postId?'Editar publicación':'Nueva publicación'}</h1></div><div className="flex flex-wrap gap-2"><button onClick={()=>void save('draft')} disabled={saving} className="border border-borde/20 px-4 py-2">Guardar borrador</button><button onClick={()=>void save('in_review')} disabled={saving} className="bg-rojo-base px-4 py-2 font-bold text-hueso">Enviar a revisión</button>{canPublish?<><button onClick={()=>void save('scheduled')} disabled={saving||!post.publishAt} className="border border-acento px-4 py-2 text-texto-principal disabled:opacity-40">Programar</button><button onClick={()=>void save('published')} disabled={saving} className="bg-rojo-base px-4 py-2 font-bold text-hueso">Publicar</button></>:null}</div></div>
  {message?<p className="mt-5 bg-superficie-elevada p-3 text-texto-principal">{message}</p>:null}{error?<p className="mt-5 bg-rojo-base p-3 text-hueso">{error}</p>:null}
  {postId&&canPublish?<div className="mt-4 flex flex-wrap gap-2 border-t border-borde/10 pt-4"><button type="button" onClick={()=>void save('rejected')} disabled={saving} className="border border-naranja px-4 py-2 text-sm text-naranja">Rechazar borrador</button><button type="button" onClick={()=>void save('unpublished')} disabled={saving} className="border border-borde/20 px-4 py-2 text-sm">Despublicar</button><button type="button" onClick={()=>void save('archived')} disabled={saving} className="border border-borde px-4 py-2 text-sm text-rojo-base">Archivar</button></div>:null}
  <div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={()=>attachMedia('image')} className="bg-rojo-base px-4 py-2 text-sm font-bold text-hueso">Adjuntar imagen al cuerpo</button><button type="button" onClick={()=>attachMedia('video')} className="bg-rojo-base px-4 py-2 text-sm font-bold text-hueso">Adjuntar video al cuerpo</button></div>
  <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_320px]"><div className="space-y-6"><Panel title="Contenido principal"><Field label="Título"><input value={post.title??''} onChange={e=>{update('title',e.target.value);if(!postId)update('slug',normalizeSlug(e.target.value));}} /></Field><Field label="Slug"><input value={post.slug??''} onChange={e=>update('slug',normalizeSlug(e.target.value))}/></Field><Field label="Bajada / resumen"><textarea rows={4} value={post.excerpt??''} onChange={e=>update('excerpt',e.target.value)}/></Field></Panel>
  <Panel title="Cuerpo por bloques"><div className="flex flex-wrap gap-2">{(['paragraph','subtitle','image','quote','list','link','cta','video'] as const).map(t=><button key={t} type="button" onClick={()=>addBlock(t)} className="border border-borde/15 px-3 py-2 text-xs capitalize">+ {t}</button>)}</div><div className="mt-5 space-y-3">{(post.bodyBlocks??[]).map((block,index)=><div key={block.id} className="border border-borde/10 bg-superficie-elevada p-4"><div className="mb-3 flex justify-between"><strong className="text-xs uppercase text-texto-principal">{block.type}</strong><div className="flex gap-3"><button onClick={()=>move(index,-1)}>↑</button><button onClick={()=>move(index,1)}>↓</button><button onClick={()=>update('bodyBlocks',(post.bodyBlocks??[]).filter((_,i)=>i!==index))}>×</button></div></div>{'text' in block?<textarea rows={block.type==='paragraph'?5:2} value={block.text} onChange={e=>changeBlock(index,{text:e.target.value})}/>:block.type==='image'?<><input placeholder="URL de imagen" value={block.url} onChange={e=>changeBlock(index,{url:e.target.value})}/><input className="mt-2" placeholder="Texto alternativo" value={block.alt} onChange={e=>changeBlock(index,{alt:e.target.value})}/></>:block.type==='list'?<textarea value={block.items.join('\n')} onChange={e=>changeBlock(index,{items:e.target.value.split('\n')})}/>:<><input placeholder="Etiqueta" value={block.label} onChange={e=>changeBlock(index,{label:e.target.value})}/><input className="mt-2" placeholder="URL segura" value={block.url} onChange={e=>changeBlock(index,{url:e.target.value})}/></>}</div>)}</div></Panel></div>
  <aside className="space-y-6"><Panel title="Ficha"><Field label="Tipo"><select value={post.postType} onChange={e=>update('postType',e.target.value as EditorialPostType)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Categoría"><input value={post.category??''} onChange={e=>update('category',e.target.value)}/></Field><Field label="Etiquetas separadas por coma"><input value={(post.tags??[]).join(', ')} onChange={e=>update('tags',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></Field><Field label="Firma"><input value={post.byline??''} onChange={e=>update('byline',e.target.value)}/></Field><Field label="Fecha de programación"><input type="datetime-local" value={post.publishAt?.slice(0,16)??''} onChange={e=>update('publishAt',e.target.value?new Date(e.target.value).toISOString():'')}/></Field></Panel>
  <Panel title="Imagen principal"><button type="button" onClick={()=>setMediaTarget({kind:'image'})} className="mb-4 border border-acento px-4 py-2 text-sm text-texto-principal">Seleccionar de Multimedia</button><Field label="URL"><input value={post.coverImageUrl??''} onChange={e=>update('coverImageUrl',e.target.value)}/></Field><Field label="Texto alternativo obligatorio"><input value={post.coverImageAlt??''} onChange={e=>update('coverImageAlt',e.target.value)}/></Field><Field label="Pie de foto"><input value={post.coverCaption??''} onChange={e=>update('coverCaption',e.target.value)}/></Field></Panel>
  <Panel title="SEO y compartir"><Field label="Título SEO"><input value={post.seoTitle??''} onChange={e=>update('seoTitle',e.target.value)}/></Field><Field label="Descripción SEO"><textarea value={post.seoDescription??''} onChange={e=>update('seoDescription',e.target.value)}/></Field><Field label="Imagen social"><input value={post.shareImageUrl??''} onChange={e=>update('shareImageUrl',e.target.value)}/></Field></Panel>
  <Panel title="Transparencia"><label className="flex gap-3"><input type="checkbox" checked={post.isSponsored??false} onChange={e=>update('isSponsored',e.target.checked)}/>Contenido patrocinado</label>{post.isSponsored?<><Field label="Etiqueta"><input value={post.sponsorLabel??''} onChange={e=>update('sponsorLabel',e.target.value)}/></Field><Field label="Declaración"><textarea value={post.sponsorshipDisclosure??''} onChange={e=>update('sponsorshipDisclosure',e.target.value)}/></Field></>:null}</Panel></aside></div>
 {mediaTarget?<MediaAssetPicker kind={mediaTarget.kind} onClose={()=>setMediaTarget(null)} onSelect={(asset)=>{if(mediaTarget.index===undefined){update('coverImageUrl',asset.publicUrl);update('coverImageAlt',asset.altText);update('credits',asset.credit);}else{changeBlock(mediaTarget.index,{url:asset.publicUrl,...(mediaTarget.kind==='image'?{alt:asset.altText}:{})});}setMediaTarget(null)}}/>:null}</div></main>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="border border-borde/10 bg-superficie-elevada p-5"><h2 className="mb-5 text-lg font-semibold">{title}</h2>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mb-4 block text-sm text-texto-largo"><span className="mb-2 block">{label}</span><div className="[&_input]:w-full [&_input]:border [&_input]:border-borde/15 [&_input]:bg-superficie-elevada [&_input]:p-3 [&_select]:w-full [&_select]:border [&_select]:border-borde/15 [&_select]:bg-superficie-elevada [&_select]:p-3 [&_textarea]:w-full [&_textarea]:border [&_textarea]:border-borde/15 [&_textarea]:bg-superficie-elevada [&_textarea]:p-3">{children}</div></label>}
