import path from 'node:path';
import { mkdir,writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { detectFinancialDivergence,mapLegacyStatus } from '../engines/financialAuthorityEngine';
import type { ProjectBudgetLine,ProjectGraph } from '../types/project';
import type { CanonicalFinancialItem,FinancialMigrationPreview,MigrationCandidate,Money } from '../types/financialAuthority';

try{process.loadEnvFile(path.join(process.cwd(),'.env.local'));}catch{}
const command=process.argv[2]??'preview';
const base=process.env.NEXT_PUBLIC_SUPABASE_URL,serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!base||!serviceKey)throw new Error('Se requiere NEXT_PUBLIC_SUPABASE_URL y SUPABASE_SERVICE_ROLE_KEY en un entorno administrativo. La clave publicable no permite backup ni inventario completo.');
const administrativeBase=base;
const headers={apikey:serviceKey,authorization:`Bearer ${serviceKey}`,accept:'application/json'};
const stamp=new Date().toISOString().replace(/[:.]/g,'-');const outputDir=path.join(process.cwd(),'out','financial-activation',stamp);

interface ProjectRow{id:string;title:string;graph:ProjectGraph;updated_at:string}
interface BudgetRow{[key:string]:unknown;id:string;project_id:string;direction:'income'|'expense';category:string;subcategory?:string;concept:string;description:string;quantity:number;unit:string;unit_value:number;discount:number;vat:number;withholding:number;other_taxes:number;total:number;currency?:string;status:CanonicalFinancialItem['status'];funding_source?:string;provider_name?:string;responsible_profile_id?:string;related_work_item_id?:string;estimated_date?:string;actual_date?:string;period?:string;notes:string;support_document_url?:string;invoice_url?:string;cost_center?:string;source?:CanonicalFinancialItem['source'];source_knowledge_ids?:string[];proposal_id?:string;idempotency_key?:string;version?:number;created_at:string;updated_at:string}

async function get<T>(resource:string){const response=await fetch(`${base}/rest/v1/${resource}`,{headers});if(!response.ok)throw new Error(`Supabase ${response.status}: ${(await response.text()).slice(0,400)}`);return await response.json() as T;}
async function getOptional<T>(resource:string){const response=await fetch(`${base}/rest/v1/${resource}`,{headers});const body=await response.text();if(!response.ok){if(response.status===404&&body.includes('PGRST205'))return{rows:[] as T,schemaState:'absent' as const};throw new Error(`Supabase ${response.status}: ${body.slice(0,400)}`);}return{rows:JSON.parse(body) as T,schemaState:'present' as const};}
const sha256=(value:string)=>createHash('sha256').update(value).digest('hex');
const money=(amount:number,currency:string):Money=>({amount:Number(amount??0),currency});
function canonical(row:BudgetRow):CanonicalFinancialItem{const currency=row.currency??'COP';return{id:row.id,projectId:row.project_id,direction:row.direction,category:row.category,subcategory:row.subcategory,concept:row.concept,description:row.description,quantity:Number(row.quantity),unit:row.unit,unitPrice:money(Number(row.unit_value),currency),discount:money(Number(row.discount),currency),vat:money(Number(row.vat),currency),withholding:money(Number(row.withholding),currency),otherTaxes:money(Number(row.other_taxes),currency),total:money(Number(row.total),currency),status:row.status,fundingSource:row.funding_source,provider:row.provider_name,responsibleId:row.responsible_profile_id,relatedWorkItemId:row.related_work_item_id,expectedDate:row.estimated_date,actualDate:row.actual_date,period:row.period,notes:row.notes,evidence:[],supportDocumentUrl:row.support_document_url,invoiceUrl:row.invoice_url,costCenter:row.cost_center,source:row.source??'manual',sourceKnowledgeIds:row.source_knowledge_ids??[],proposalId:row.proposal_id,idempotencyKey:row.idempotency_key??`legacy-table:${row.id}`,version:Number(row.version??1),createdAt:row.created_at,updatedAt:row.updated_at};}
function candidate(projectId:string,line:ProjectBudgetLine):MigrationCandidate{const currency='COP',zero=money(0,currency);return{projectId,source:{kind:'graph',lineId:line.id},target:{projectId,direction:'expense',category:line.category,concept:line.concept,description:'Candidate from graph.tools.budgetLines; not migrated.',quantity:line.quantity,unit:line.unit,unitPrice:money(line.unitValue,currency),discount:zero,vat:money(line.quantity*line.unitValue*line.vatRate/100,currency),withholding:money(line.quantity*line.unitValue*line.withholdingRate/100,currency),otherTaxes:money(line.otherTaxes,currency),total:money(line.quantity*line.unitValue*(1+line.vatRate/100-line.withholdingRate/100)+line.otherTaxes,currency),status:mapLegacyStatus(line.status),provider:line.provider,responsibleId:undefined,expectedDate:line.estimatedDate,actualDate:line.actualDate,notes:'',evidence:[],source:line.source==='manual'?'manual':'system',sourceKnowledgeIds:[]},confidence:.65,classification:'REVIEW',warnings:['Legacy graph no distingue income/expense; expense es solo un preview.','responsible es texto y no puede mapearse con seguridad a profile UUID.','IVA y retención son porcentajes en graph y montos en la tabla. Requiere revisión.']};}

async function main(){const [projects,budgetResult]=await Promise.all([get<ProjectRow[]>('projects?select=id,title,graph,updated_at&order=id'),getOptional<BudgetRow[]>('project_budget_lines?select=*&order=project_id,id')]);const rows=budgetResult.rows;await mkdir(outputDir,{recursive:true});
  if(command==='backup'){const environment={supabaseHost:new URL(administrativeBase).host,projectRef:new URL(administrativeBase).host.split('.')[0],label:process.env.FINANCIAL_ACTIVATION_ENVIRONMENT??'unknown'};if(environment.label==='unknown')throw new Error('Define FINANCIAL_ACTIVATION_ENVIRONMENT con una etiqueta verificada (por ejemplo staging). El backup no continúa contra un entorno desconocido.');const resources:Array<[string,string,unknown[],string]>=[['projects-graph.json','projects',projects,budgetResult.schemaState],['project-budget-lines.json','project_budget_lines',rows,budgetResult.schemaState]];for(const table of ['profiles','project_applications','project_actor_links','project_editorial_profiles','project_reanalysis_audits','project_snapshots','funding_applications']){const result=await getOptional<Record<string,unknown>[]>(`${table}?select=*`);resources.push([`${table}.json`,table,result.rows,result.schemaState]);}const files=[] as Array<{name:string;table:string;records:number;schemaState:string;sha256:string}>;for(const[name,table,data,schemaState]of resources){const json=JSON.stringify(data,null,2);files.push({name,table,records:data.length,schemaState,sha256:sha256(json)});await writeFile(path.join(outputDir,name),json,'utf8');}const manifest={createdAt:new Date().toISOString(),readOnlySource:true,environment,tables:files.length,totalRecords:files.reduce((sum,file)=>sum+file.records,0),files};await writeFile(path.join(outputDir,'manifest.json'),JSON.stringify(manifest,null,2),'utf8');print({command,status:'created',outputDir,createdAt:manifest.createdAt,environment,tables:manifest.tables,totalRecords:manifest.totalRecords,files:files.map(({name,table,records,schemaState,sha256})=>({name,table,records,schemaState,sha256}))});return;}
  if(command!=='preview')throw new Error('Usa preview o backup. Ambos son read-only sobre Supabase.');const resultProjects:FinancialMigrationPreview['projects']=[];
  for(const project of projects){const legacy=project.graph?.tools?.budgetLines??[],items=rows.filter(row=>row.project_id===project.id).map(canonical),report=detectFinancialDivergence(project.id,legacy,items);const graphOnly=report.divergences.filter(d=>d.kind==='graph_only');const conflicts=report.divergences.filter(d=>['value_mismatch','status_mismatch','tax_mismatch','total_mismatch','responsible_mismatch'].includes(d.kind));const safeMatches=Math.max(0,legacy.length-graphOnly.length-new Set(conflicts.map(d=>d.graphLineId).filter(Boolean)).size);resultProjects.push({projectId:project.id,projectTitle:project.title,legacyLines:legacy.length,canonicalLines:items.length,safeMatches,potentialMigrations:graphOnly.map(divergence=>candidate(project.id,legacy.find(line=>line.id===divergence.graphLineId)!)),conflicts:conflicts.length,ignored:report.divergences.filter(d=>d.kind==='table_only').length,warnings:graphOnly.length?['Candidate migrations require explicit human approval; no writes were performed.']:[],divergences:report.divergences});}
  const totals=resultProjects.reduce((a,p)=>({projects:a.projects+1,legacyLines:a.legacyLines+p.legacyLines,canonicalLines:a.canonicalLines+p.canonicalLines,safeMatches:a.safeMatches+p.safeMatches,potentialMigrations:a.potentialMigrations+p.potentialMigrations.length,conflicts:a.conflicts+p.conflicts,ignored:a.ignored+p.ignored}),{projects:0,legacyLines:0,canonicalLines:0,safeMatches:0,potentialMigrations:0,conflicts:0,ignored:0});const preview:FinancialMigrationPreview={generatedAt:new Date().toISOString(),readOnly:true,projects:resultProjects,totals};await writeFile(path.join(outputDir,'migration-preview.json'),JSON.stringify(preview,null,2),'utf8');print({command,status:'created',output:path.join(outputDir,'migration-preview.json'),totals});}
function print(value:unknown){process.stdout.write(`${JSON.stringify(value,null,2)}\n`);}void main().catch(error=>{process.stderr.write(`${error instanceof Error?error.stack:error}\n`);process.exitCode=1;});
